Feature: bang & external bang can be written in upper case
searxng/searxng pull request #1236
Opened 2022-05-24 21:46 UTC by dalf

## What does this PR do?

See #1223 : currently `!DDG` or `!Dgg` is not seen as bang, however on phone keyboard might switch to upper case as a exclamation mark.

## Why is this change important?

Easier usage on a phone.

## How to test this PR locally?

Try `!DDG time` or `!Dgg time`.

## Author's checklist

engine name are already forced in lower case: https://github.com/searxng/searxng/blob/fddbc5ed00ded5f28ef3b643686e7c177a3a75ce/searx/engines/__init__.py#L113-L116

## Related issues

Close #1223

2022-05-25 05:43 UTC, return42 requested changes
The patch itself works, but upper case categories do no longer work:

```diff
modified   searx/settings.yml
@@ -246,6 +246,7 @@ categories_as_tabs:
   science:
   files:
   social media:
+  TV:
 
 engines:
   - name: apk mirror
@@ -1611,7 +1612,8 @@ engines:
   - name: mediathekviewweb
     engine: mediathekviewweb
     shortcut: mvw
-    disabled: true
+    disabled: false
+    categories: [TV]
```

Before this patch `!TV` did worked, with this patch neither `!tv` nor `!TV` do work.

IMO we should also support lower case bangs (`!tv`) for a category with upper case letters (`TV`). But we should not lower case the category name in the UI (hint: new categories do not have a translation).

2023-02-10 14:39 UTC, return42 commented
Are there any interest to reactivate this PR .. or should we just close it?

2023-03-05 08:19 UTC, return42 commented
ready for review?

2023-09-21 06:25 UTC, Bnyro commented
That's a very neat improvement! 🚀 

Could we please revive/continue this?

2025-05-02 08:40 UTC, dalf commented
See https://github.com/searxng/searxng/commit/c6c6d3027cbdfa47ad435adb384e753497e059ab

2025-05-02 08:40 UTC, closed without merging