Petal images
searxng/searxng pull request #1259
Opened 2022-05-31 15:42 UTC by allendema

## What does this PR do?

Add engine to get results from Petalsearch Images.

## Why is this change important?
More image engines to choose.

## How to test this PR locally?
Do a search with it, like so:

```!pti mark normand```

## Author's checklist
N/A

## Related issues
https://github.com/searxng/searxng/issues/1257

2022-05-31 15:51 UTC, tiekoetter commented
@allendema Please reformat with `make format.python`

2022-05-31 19:25 UTC, tiekoetter requested changes

2022-05-31 19:25 UTC, tiekoetter commented on searx/settings.yml
> +  - name: petal images
```suggestion
  - name: petalsearch images
```

2022-05-31 19:25 UTC, tiekoetter commented on searx/settings.yml
> +  - name: petal images
For reference: https://github.com/searxng/searxng/blob/51ba817e06bb15ca1768010d6873d1d7bf48b0b6/searx/settings.yml#L1723

2022-05-31 19:25 UTC, tiekoetter commented on searx/settings.yml
> +    shortcut: pti
```suggestion
    shortcut: ptsi
```

2022-05-31 19:25 UTC, tiekoetter commented on searx/settings.yml
> +    shortcut: pti
For reference: https://github.com/searxng/searxng/blob/51ba817e06bb15ca1768010d6873d1d7bf48b0b6/searx/settings.yml#L1724

2022-05-31 21:24 UTC, tiekoetter approved these changes
LGTM

2022-06-02 12:54 UTC, return42 reviewed
@allendema thanks a lot for adding petalsearch image engine .. its a very fast engine (google fells ponderous compared) .. I left nodes about some nits (I fixed) .. I am going to merge :+1:

2022-06-02 12:54 UTC, return42 commented on searx/engines/petal_images.py
> +    &ss_mode={safesearch}&ss_type=normal'
FYI: This will add 4 (white-) spaces to the URL / I fixed it.

2022-06-02 12:54 UTC, return42 commented on searx/settings.yml
> +      results: JSON
FYI: I moved this to the python code.

2022-06-02 12:54 UTC, return42 commented on searx/settings.yml
> +    categories: images
FYI: this is already defined in the python code / I removed this lines.

2022-06-02 12:59 UTC, merged