Theme: add a preference to center the results
searxng/searxng pull request #1281
Opened 2022-06-03 12:24 UTC by dalf

## What does this PR do?

Add a new preference "Center alignment":
![image](https://user-images.githubusercontent.com/1594191/171851455-ab2d8021-399f-46e2-9879-e01d7ed9e12c.png)

When enabled, the results are centered instead of being in the left (or right) side of the screen.

![image](https://user-images.githubusercontent.com/1594191/171851682-9b8f5984-ae31-4a0f-9ce5-2e52f8ba2ea6.png)

![image](https://user-images.githubusercontent.com/1594191/171851768-512e21a5-3818-4f0d-b7c5-c5ba3f5f4a41.png)

![image](https://user-images.githubusercontent.com/1594191/171851922-40f5f2b4-68a0-4c26-ad4b-15b57053b7ae.png)

![image](https://user-images.githubusercontent.com/1594191/171851986-291416cb-aba1-407b-9376-7723e0f550f3.png)

A new CSS is added  in base.html:
```jinja2
<html class="no-js theme-{{ preferences.get_value('simple_style') or 'auto' }} center-aligment-{{ preferences.get_value('center_aligment') and 'yes' or 'no' }}" lang="{{ locale_rfc5646 }}" {% if rtl %} dir="rtl"{% endif %}>
```

There is a new LESS file : searx/static/themes/simple/src/less/style-center.less

## Why is this change important?

Highly requested feature.

## How to test this PR locally?

## Author's checklist

The result width is hard coded.
Another can add another preference to set the result width.

For reference in DDG:
![image](https://user-images.githubusercontent.com/1594191/171852990-4e859ac2-da7f-4f14-9017-5858579dc92e.png)

## Related issues

Related to #1169

2022-06-03 13:13 UTC, dalf commented
I'm sorry I've pushed force to update the PR: on the previous version:
* everything was centered including the other pages (preferences, info pages, etc...).
* the back to top button was not in the right place

2022-06-03 14:46 UTC, return42 requested changes
With results on left side, the results are in-line with the seaerch-box:

![grafik](https://user-images.githubusercontent.com/554536/171873623-b8baf81d-3f4f-45d8-b91c-48e0bf50ed36.png)

in the centred layout the search-box is no longer in-line withe the result list / the entire header is moved to the right:

![grafik](https://user-images.githubusercontent.com/554536/171874118-a6423399-6404-4e0c-9079-a5cd40534020.png)

When images are shown in a cateory different to "images" ..

![grafik](https://user-images.githubusercontent.com/554536/171877340-911ae4e7-34ba-4478-a27c-23d14461415d.png)


the result list on the left side is shown only partial:

![grafik](https://user-images.githubusercontent.com/554536/171877520-68239569-ddf8-420a-83ea-500ce281d49a.png)

2022-06-03 15:56 UTC, dalf commented
Updated:

> With results on left side, the results are in-line with the seaerch-box

![image](https://user-images.githubusercontent.com/1594191/171901639-673a3499-14d2-416c-bea3-8d0557f436e1.png)

> When images are shown in a cateory different to "images" ..

![image](https://user-images.githubusercontent.com/1594191/171901728-f37fd2e0-1a5a-4c27-a722-2b387e7a240d.png)

( the style-center.less is still full of magic values, but at least if we agree on the layout that's a start )

2022-06-03 16:17 UTC, return42 commented
Sorry for being pedantic .. its more a question:  does it makes sense / is it possible to move result list to the left when there is an image shown?

Or with other words .. whenever I image is shown the layout of the left result list and the image box on the right should be the same nevertheless what the value of `center_aligment` is.

ATM with `center_aligment=true` it looks like this  ..

![grafik](https://user-images.githubusercontent.com/554536/171904739-e0c0a7e9-3bc3-4f2c-a265-bfbd531fc678.png)

there is a lot of *unused* space on the left side .. when disabling `center_aligment=false`, the space is better used:

![grafik](https://user-images.githubusercontent.com/554536/171905077-4e4ed58a-aade-4959-8ce8-a8d0aad84db6.png)

2022-06-03 16:42 UTC, dalf commented
>  does it makes sense / is it possible to move result list to the left when there is an image shown?

Yes that's doable. I'm not sure what is the best option.

Detail closed:

![image](https://user-images.githubusercontent.com/1594191/171909217-16682dfe-b9a9-44df-948d-54dd9e40edb1.png)

Detail opened (notice the search box & the filters are still centered):

![image](https://user-images.githubusercontent.com/1594191/171909272-b4fb43dd-e571-48f6-b4db-1dc96ca3e33a.png)


<details>

<summary>searx/static/themes/simple/src/less/style-center.less</summary>

Notice the `--center-screen-width` variable to adjust the width (implement another request of the issue #1169 )

```less
@media screen and (min-width: @tablet) {
  .center-aligment-yes #main_results {
    display: flex;
    flex-direction: column;
    align-items: center;

    --center-screen-width: 75rem; // override the less variable @results-width = 45rem

    #search {
      width: 100%;
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    #search_header {
      grid-template-columns: calc(50% - 4.5rem - var(--center-screen-width) / 2) 3rem var(--center-screen-width);
      grid-template-areas: "na logo search" "na spacer categories";
      width: 100%;
      padding-left: 0;
      padding-right: 0;
    }

    .search_filters {
      .ltr-margin-left(0.5rem);
      width: var(--center-screen-width);
    }

    #results {
      grid-template-columns: calc(var(--center-screen-width) - 30rem) 25rem;

      &.image-detail-open {
        grid-template-columns: @results-width 25rem;
      }

      &.only_template_images,
      &.image-detail-open {
        align-self: flex-start;
      }

      &:not(.only_template_images):not(.image-detail-open) {
        .ltr-margin-left(1.5rem);

        #backToTop {
          .ltr-left(calc(50% - 30rem + var(--center-screen-width) / 2));
        }
      }

      .result .content {
        max-width: inherit;
      }
    }
  }
}
```
</detail>

2022-06-03 17:23 UTC, return42 commented
> notice the search box & the filters are still centered

Its not a drawback .. its a feature :-) .. IMO it is better the search box resist on its position .. when the search box moves its position the user has to look out where it is ..

Do you like to patch this PR?

2022-06-03 17:49 UTC, dalf commented
> Do you like to patch this PR?

Done.

There is a new CSS variable `--center-screen-width` to declare the screen width and to remove the magic values (see issue https://github.com/searxng/searxng/issues/1169 ). The layout works as expect if the value is changed using the devtools (it is going to be an user preference in the future). This is half backed IMO because:
* it mixes CSS variables and LESS variables.
* the sidebar width is hardcoded to 25rem without a variable, so it is copy / paste.

2022-06-03 18:00 UTC, return42 approved these changes
> This is half backed IMO because:

Its perfect for now .. lets merge :+1:

2022-06-03 18:08 UTC, dalf commented
I would like @mrpaulblack  's opinion on the code.

@unixfox feel free to add a comment

2022-06-03 21:15 UTC, mrpaulblack commented
Is it ok if I review this tomorrow? The idea I have: I would like to have the center result option which will also make the results larger in width at the same time. This should IMO be one toggle in the preferences setting both at the same time... (having a custom field to specify the width of the results is IMO to much) :+1:

2022-06-04 06:44 UTC, dalf commented
> I would like to have the center result option which will also make the results larger in width at the same time.

does the user have to center the results to choose the page width?
or would the different combo exists?
* not center - normal
* not center - large
* center - normal
* center - large
?

2022-06-04 06:49 UTC, mrpaulblack commented
I think there should be 2 options:
* not center - normal
and
* center - large

(center result width should be not bigger then the total width of the screen when switching to tablet UI IMO, otherwise we would need another `large desktop` size or something). I think with this we would not overload the user with options (that we also need to maintain btw), while still providing something for oscar and simple fans alike...

2022-06-04 06:58 UTC, dalf commented
Ok, make sense.

In Oscar:

| @media (min-width: ... )| container width |
| - | - |
| 1280px | 1170px |
| 992px | 970px |
| 768px | 750px |

`style-center.less` can do that.

2022-06-04 07:09 UTC, dalf commented
1280px = 80rem --> only the width of 1170px is going to be used, otherwise the theme switches to the tablet mode.

https://github.com/searxng/searxng/blob/c17c7dc0504daa6be675de6ac08fed03ef3246f7/searx/static/themes/simple/src/less/definitions.less#L257-L262

( I think what Oscar's users would like is to be able to disable the tablet mode )

2022-06-04 08:16 UTC, dalf commented
I've created another branch (*) : where the tablet layout is disabled (only when "Center alignment" is enabled)

With a 1000px width (Tor Browser default width):

| style-oscar branch | Oscar | master & style-center branches |
| - | - | - |
| ![image](https://user-images.githubusercontent.com/1594191/171990614-0c9d5951-a3d5-42c4-98e1-5243ec811d93.png) |  ![image](https://user-images.githubusercontent.com/1594191/171990651-7cf1b954-0ada-467d-b42e-3edde99f9704.png) | ![image](https://user-images.githubusercontent.com/1594191/171990849-86e3d65f-e454-4128-835a-2b50dd174011.png) |


---
* https://github.com/dalf/searxng/tree/style-oscar
* https://github.com/searxng/searxng/commit/13a893022cf3c6ada4180b7fba6da26bdc4b2472

2022-06-04 10:46 UTC, unixfox commented
Thank you @dalf, it's already a good step towards my wishes from #1169!

Now that I discovered the DDG settings page (https://duckduckgo.com/settings), I really like the way the search bar is centered like you also shown in https://github.com/searxng/searxng/issues/1169#issuecomment-1126696026

![image](https://user-images.githubusercontent.com/4016501/171995356-0759a16f-4633-48cc-b6a4-fa2738992948.png)

-------

> I've created another branch (*) : where the tablet layout is disabled (only when "Center alignment" is enabled)
> 
> Screenshoots with a with of 1000px (the Tor Browser default width):
> style-oscar branch 	Oscar 	master & style-center branches
> ![image](https://user-images.githubusercontent.com/1594191/171990614-0c9d5951-a3d5-42c4-98e1-5243ec811d93.png) 	![image](https://user-images.githubusercontent.com/1594191/171990651-7cf1b954-0ada-467d-b42e-3edde99f9704.png) 	![image](https://user-images.githubusercontent.com/1594191/171990849-86e3d65f-e454-4128-835a-2b50dd174011.png)
> 
>     * [https://github.com/dalf/searxng/tree/style-oscar](https://github.com/dalf/searxng/tree/style-oscar?rgh-link-date=2022-06-04T08%3A16%3A01Z)
> 
>     * [13a8930](https://github.com/searxng/searxng/commit/13a893022cf3c6ada4180b7fba6da26bdc4b2472)

I do agree with that, a screen of 1000px is already small so if we can have as much space taken by the texts as possible (like it's already possible on oscar) that would be great.

2022-06-05 06:41 UTC, dalf commented on searx/templates/simple/preferences.html
> +      <div class="description">{{ _('Displays results in the center of the page (Oscar layout).') }}</div>
The description contains a reference to the Oscar layout.

2022-06-05 06:41 UTC, dalf commented on searx/static/themes/simple/src/less/definitions.less
> +@results-sidebar-width: 25rem;
New variable, so style-center.less can reuse this value

2022-06-05 06:45 UTC, dalf commented
The PR has been updated:
* starting from the @phone screen width, the layout is similar to the Oscar theme.
* most of the magic values have been replaced by variables.
* the description in the preferences makes a reference to the Oscar theme.

> I really like the way the search bar is centered like you also shown in https://github.com/searxng/searxng/issues/1169#issuecomment-1126696026

I'm not sure how to center the filters (language, date, safe search), so for now the PR keeps the Oscar layout.

2022-06-05 13:21 UTC, unixfox commented
IMO the images section shouldn't change and be like when "centered results" is not enabled.

![image](https://user-images.githubusercontent.com/4016501/172052543-0ba765ad-9533-427c-9118-4b2b6ca2456e.png)

This feels weird.

2022-06-05 18:01 UTC, dalf commented
> This feels weird.

that was not intended.

I've updated the PR, it should be working now.

2022-06-05 18:53 UTC, unixfox approved these changes

2022-06-05 19:39 UTC, merged

2022-07-02 23:06 UTC, amalgame21 commented
Minor question
center_aligment, seems missing "n"?
Just figure it out from the setting.yml file

2022-07-03 06:56 UTC, return42 commented
> center_aligment, seems missing "n"?

@amalgame21 its not clear to me what you mean by / this is a YAML file and the value of this option is a boolean (`true` or `false`).

But your comment reminds me that the documentation of this option is missed .. thanks :-) .. I created https://github.com/searxng/searxng/issues/1420

2022-07-03 07:31 UTC, dalf commented
@return42 , it's everywhere:

https://github.com/searxng/searxng/blob/4ef62637256d4b2966ff7f0be0051e02d545f756/searx/settings.yml#L95

https://github.com/searxng/searxng/blob/4ef62637256d4b2966ff7f0be0051e02d545f756/searx/settings_defaults.py#L188

https://github.com/searxng/searxng/blob/4ef62637256d4b2966ff7f0be0051e02d545f756/searx/templates/simple/base.html#L2

It should be "center_alignment" with a `n`.

We can fix the variable names, the settings name is more tricky: administrator will have hard time to figure out the typo.

2022-07-03 07:33 UTC, unixfox commented
> @return42 , it's everywhere:
> 
> https://github.com/searxng/searxng/blob/4ef62637256d4b2966ff7f0be0051e02d545f756/searx/settings.yml#L95
> 
> https://github.com/searxng/searxng/blob/4ef62637256d4b2966ff7f0be0051e02d545f756/searx/settings_defaults.py#L188
> 
> https://github.com/searxng/searxng/blob/4ef62637256d4b2966ff7f0be0051e02d545f756/searx/templates/simple/base.html#L2
> 
> It should be "center_alignment" with a `n`.
> 
> We can fix the variable names, the settings name is more tricky: administrator will have hard time to figure out the typo.

I think the feature is pretty new that it's ok to fix this typo. This will affect a very small amount of people.

2022-07-03 07:39 UTC, return42 commented
> I think the feature is pretty new that it's ok to fix this typo. This will affect a very small amount of people.

Ooops, sorry I haven't seen the typo `center_aligment` needs to be fixed --> `center_alignment`

@dalf do you have time to prepare a patch? .. otherwise I will take the time today ..

2022-07-03 08:35 UTC, dalf commented
> do you have time to prepare a patch?

I won't have time today.