Add privacypolicy_url option
searxng/searxng pull request #1329
Opened 2022-06-15 19:59 UTC by samsaptidev

## What does this PR do?

This PR adds a `privacypolicy_url` option to `settings.yml`. It allows the instance maintainer to optionally link to a privacy policy for their instance.

## Why is this change important?

It is important for the end user to know about the particular instance's data practices.

## How to test this PR locally?

By changing the `general.privacypolicy_url` setting.

## Author's checklist

## Related issues

Closes none, but related to #1285.

2022-06-15 20:02 UTC, tiekoetter commented
@samsaptidev Could you please squash your commits together.

2022-06-15 20:03 UTC, samsapti commented
@tiekoetter done :+1:

2022-06-15 20:06 UTC, tiekoetter requested changes

2022-06-15 20:06 UTC, tiekoetter commented on docs/admin/engines/settings.rst
> +     contact_url: false        # mailto:contact@example.com
Please revert this to the old spacing.

2022-06-15 20:06 UTC, tiekoetter commented on searx/templates/simple/base.html
> +        <a href="{{ get_setting('general.contact_url') }}">{{ _('Contact instance maintainer') }}</a>{% endif %}{% if get_setting('general.privacypolicy_url') %} |
Please start a new line.

2022-06-15 20:12 UTC, samsaptidev commented on docs/admin/engines/settings.rst
> +     contact_url: false        # mailto:contact@example.com
Done

2022-06-15 20:12 UTC, samsaptidev commented on searx/templates/simple/base.html
> +        <a href="{{ get_setting('general.contact_url') }}">{{ _('Contact instance maintainer') }}</a>{% endif %}{% if get_setting('general.privacypolicy_url') %} |
Done

2022-06-15 21:21 UTC, tiekoetter commented
@samsaptidev I have another thing where I am not sure if it should be changed or not: The "privacy policy" is after the "contact instance maintainer" link.
I personally think it would look nicer if it was in front of it because the contact url is generally an e-mail address and therefore not really clickable.

I have a similar setup in place for my instance (https://github.com/tiekoetter/searxng/commit/3549f0952e690009f50bffc21a3a08c7fb1b9b2f)

What do you think?
Apart from that everything looks good 👍

2022-06-16 06:38 UTC, return42 commented
@samsaptidev Sorry, I could have already given you the hint Matrix yesterday, but I had not thought of it at that moment:

If you want to deliver additional pages (e.g. your privacy policy) you can do it simply by adding a new file into the [searx/infopage/en](https://github.com/searxng/searxng/tree/master/searx/infopage/en) folder of your instance. The file needs to be written in Markdown markup.

Not yet implemented, a suggeestion from @dalf that is related to this topic:

- https://github.com/searxng/searxng/discussions/1330

2022-06-16 09:51 UTC, samsapti commented
@return42 As I said on Matrix too, I think we should merge this PR anyways.

The `privacypolicy_url` could remain as an override. A use case for this would be if you want to have a single privacy policy for both SearXNG and other things, such as a personal website. This is what I will be using it for personally.

2022-06-16 09:57 UTC, samsaptidev commented
@tiekoetter I have switched the contact and privacy policy links around :+1:

2022-06-16 10:22 UTC, return42 commented
> A use case for this would be if you want to have a single privacy policy for both SearXNG and other things, such as a personal website. This is what I will be using it for personally.

:thinking: seems a valid argument to me .. @dalf what do you think?

2022-06-16 10:35 UTC, tiekoetter approved these changes
LGTM 👍

2022-06-16 11:58 UTC, samsaptidev commented
Also, in the context of #1330, the `privacypolicy_url` could perhaps later be changed to have a default value of `/info/en/privacy` or something.

2022-06-18 05:26 UTC, dalf approved these changes
Thank you !
This is a great addition.

2022-06-18 05:26 UTC, merged