Move donation link
searxng/searxng pull request #1380
Opened 2022-06-29 17:36 UTC by dalf

## What does this PR do?

* The first commit allows an administrator to delete donate.md (or any .md file) without crashing the application. Note: the "Donate" link on the top right corner will still be there.
* The second commit implement the request from  #1378 (README.rst contains a link to the new donate.html page)

## Why is this change important?

In master branch, donate.md creates a confusion: the user don't know who is supported, the instance administrator or the SearXNG developpers.

## How to test this PR locally?

* `make docs.live`
* `make run`: 
  * follow the donate link.
  * delete `donate.md`, see there is no crash (only a 404 page).

## Author's checklist

## Related issues

Close #1378

2022-06-29 18:54 UTC, unixfox requested changes

2022-06-29 18:54 UTC, unixfox commented on README.rst
> +Follow the `donate <https://docs.searxng.org/donate.html>`_ link.
```suggestion
You can support the SearXNG project by clicking on the donation page: `https://docs.searxng.org/donate.html <https://docs.searxng.org/donate.html>`_
```

2022-06-29 18:54 UTC, unixfox commented on docs/donate.rst
> +If there is enough fund we can ask for a security audit or pay an UX designer.
```suggestion
If there is enough fund we can ask for a security audit or pay an User Experience (UX) designer.
```

2022-06-29 18:54 UTC, unixfox commented on searx/infopage/en/donate.md
> +You can support the developpers of SearXNG following this [link](https://docs.searxng.org/donate.html)
```suggestion
You can support the SearXNG project by clicking on the donation page: [https://docs.searxng.org/donate.html](https://docs.searxng.org/donate.html)
```

2022-06-29 19:51 UTC, unixfox approved these changes

2022-06-29 20:16 UTC, merged

2022-07-01 16:35 UTC, return42 commented
@dalf sorry for my late response on this PR / I had been in vacation the last days.

I have some remarks about this PR (and https://github.com/searxng/searxng/pull/1369)

1. I think it is not consistent to add description to the "about" and the "donation" icon while the preference icon does not have a description / I think it is better to remove all descriptions

![grafik](https://user-images.githubusercontent.com/554536/176928777-9a11c567-7e6c-43b3-9e87-fa6b375418e8.png)

2. I think the question mark does not fit for a link to the "about" page / a question mark fits better for a link to the "search syntax" page.  I think "info" icon fits better for about

![grafik](https://user-images.githubusercontent.com/554536/176931483-2c81b9df-d3db-4c95-a4e5-9043a99e36ad.png) 

4. Is the infopage that does nothing more then offer a link to the SearXNG project needed? Isn't it better the donation icon links directly to https://docs.searxng.org/donate.html ?

5. I think in the documentation, in the "Why donating?" section, we should only document for what we use the donation (we use it for the costs of the infrastructure) .. we should not decide today what we will do if we receive "more" donations.  We do not know today what we may need tomorrow or what the community may want. / See my diff below, where I also fixed some markups and indentations.

@unixfox, @mrpaulblack what do you think?



```diff --git a/docs/donate.rst b/docs/donate.rst
index b68ed807b..3610320b5 100644
--- a/docs/donate.rst
+++ b/docs/donate.rst
@@ -1,35 +1,31 @@
+=====================
 Donate to searxng.org
 =====================
 
-Why donating?
--------------
-
 If you want to support the SearXNG team you can make a donation.
 
-This will help us to pay the costs for:
-
-- the two VPS servers for searx.space
-- the domain names (searxng.org and searx.space)
-- the protonmail account
-
-If there is enough fund we can ask for a security audit or pay an User Experience (UX) designer.
 
-Payment methods
----------------
-
--  Credit/debit card and bank transfer
+Why donating?
+=============
 
-   -  `Liberapay`_ (recurrent donation)
-   -  `Buy Me a Coffee`_ (one time donation)
+Your donation helps us cover the costs of running the infrastructure of
+searxng.org and searx.space.
 
--  Cryptocurrency
 
-   -  Bitcoin: `bc1qn3rw8t86h05cs3grx2kmwmptw9k4kt4hyzktqj`_ (Segwit
-      compatible)
-   -  Bitcoin cash: `qpead2yu482e3h9amy5zk45l8qrfhk59jcpw3cth9e`_
-   -  Ethereum: `0xCf82c7eb915Ee70b5B69C1bBB5525e157F35FA43`_
-   -  Dogecoin: `DBCYS9issTt84pddXSsTHpQxyQDTFp1TE4`_
-   -  Litecoin: `ltc1q5j6x6f4f2htldhq570e353clc8fmw44ra5er5q`_
+Payment methods
+===============
+
+- Credit/debit card and bank transfer
+  - `Liberapay`_ (recurrent donation)
+  - `Buy Me a Coffee`_ (one time donation)
+
+- Cryptocurrency
+  - Bitcoin: `bc1qn3rw8t86h05cs3grx2kmwmptw9k4kt4hyzktqj`_ (Segwit
+    compatible)
+  - Bitcoin cash: `qpead2yu482e3h9amy5zk45l8qrfhk59jcpw3cth9e`_
+  - Ethereum: `0xCf82c7eb915Ee70b5B69C1bBB5525e157F35FA43`_
+  - Dogecoin: `DBCYS9issTt84pddXSsTHpQxyQDTFp1TE4`_
+  - Litecoin: `ltc1q5j6x6f4f2htldhq570e353clc8fmw44ra5er5q`_
 
 .. _Liberapay: https://liberapay.com/SearXNG/
 .. _Buy Me a Coffee: https://buymeacoffee.com/searxng
```

2022-07-01 18:22 UTC, unixfox commented
>     4. Is the infopage that does nothing more then offer a link to the SearXNG project needed? Isn't it better the donation icon links directly to [docs.searxng.org/donate.html](https://docs.searxng.org/donate.html) ?

I do agree with that.

>     5. I think in the documentation, in the "Why donating?" section, we should only document for what we use the donation (we use it for the costs of the infrastructure) .. we should not decide today what we will do if we receive "more" donations.  We do not know today what we may need tomorrow or what the community may want. / See my diff below, where I also fixed some markups and indentations.

I don't think it's bad to say what we could do with the money in the future, it gives more reasons for the user to think about donating which is great. We aren't saying that we **are going** to do it.

But I'm okay with rewording the sentences if you feel like what has been written by dalf can be improved.

2022-07-02 05:22 UTC, return42 commented
> I don't think it's bad to say what we could do with the money in the future, it gives more reasons for the user to think about donating which is great. We aren't saying that we are going to do it.

After thinking about it again I agree with your opinion.

Does anyone have a opinion about the other remarks 1., 2., and 3. ?