[mod] add 'Accept-Language' HTTP header to online processores
searxng/searxng pull request #1560
Opened 2022-07-26 11:25 UTC by return42

## What does this PR do?

[mod] add 'Accept-Language' HTTP header to online processors

## Why is this change important?

Most engines that support languages (and regions) use the Accept-Language from the WEB browser to build a response that fits to the language (and region).

## How to test this PR locally?

   make run

compare the results of engines that have language support (e.g. google) before and after the patch.  Select languages (regions) like zh-TW and zh-CN.

The results should be slightly improved (at least in my tests and on my IP).

2022-07-31 15:43 UTC, return42 commented
@dalf FYI I rebased the PR and placed https://github.com/searxng/searxng/pull/1560/commits/5015d43d049fec2eb3e6999abbe7a46f57585f04 on top / according to what we discussed on matrix.

2022-08-01 08:13 UTC, dalf requested changes
except the few issues, LGTM .

2022-08-01 08:13 UTC, dalf commented on searx/engines/openstreetmap.py
> -    params['headers']['Accept-Language'] = accept_language
* in the master branch "all" means "en" in HTTP header.
* in this PR there is no header at all.

==> 
The query `!osm :all tokyo` returns:
* `Tokyo, Japan` in the master branch
* `東京都, 日本` in this PR

Can be fixed with:
```python
if 'Accept-Language' not in params['headers']:
    params['headers']['Accept-Language'] = 'en'
```

2022-08-01 08:13 UTC, dalf commented on searx/engines/wikipedia.py
> -    if params['language'].lower() in language_variants.get(language, []):
LGTM 👍 
I see a difference between `!wp 東京都 :zh` and `!wp 東京都 :zh-hk`

2022-08-01 08:13 UTC, dalf commented on searx/engines/duckduckgo_definitions.py
> -    params['headers']['Accept-Language'] = language
`!ddd paris :fr` returns:
* a result in French in the master branch
* a result in English in this PR. I don't see the "Accept-Language" header in the log.

With `send_accept_language_header = True` it works as before.

2022-08-01 08:13 UTC, dalf commented on searx/settings.yml
> +    send_accept_language_header: true
Most of the engines have the configuration in the Python code rather than the .yml file
It would be better to add `send_accept_language_header = True` to wikipedia.py (and to other engines).

2022-08-01 08:13 UTC, dalf commented on searx/network/network.py
> +            self._logger.debug("HTTP request arguments--> %s", kwargs)
Can we discuss about this change in another PR?

* httpx might add to some additional HTTP header
* It makes the log verbose

2022-08-01 14:53 UTC, return42 commented on searx/engines/openstreetmap.py
> -    params['headers']['Accept-Language'] = accept_language
Thanks, forgot to implement the `all` case / I will fix it.

It is OT here but what me often confuse is  the designation "Default language" and the `:all` tag ...

![image](https://user-images.githubusercontent.com/554536/182177172-34248e5c-cd49-45b8-a9a6-85da7ee169bb.png)

2022-08-01 15:59 UTC, return42 commented
> except the few issues, LGTM .

Thanks for review .. I fixed the issues you reported.

2022-08-01 15:59 UTC, merged