Disabling zlibrary due to z-lib.org domain seizure
searxng/searxng pull request #1937
Opened 2022-11-06 15:31 UTC by BoxingOctopus

## What does this PR do?

Disables ZLibrary by default

## Why is this change important?

the z-lib.org domain was seized by the FBI. Leaving ZLibrary enabled causes searxng to crash on startup as a result.

## Related issues

2022-11-06 20:46 UTC, Evhorizon commented
I might be wrong but maybe just disabling it won't prevent searxng from trying to connect to it when it initializes. Maybe even better to remove the engine from the settings.yml file?

2022-11-06 20:55 UTC, dalf commented
On the [wikipedia page](https://en.wikipedia.org/wiki/Z-Library), there are two onion URL.

The category should be changed to onions like the ahmia engine:
https://github.com/searxng/searxng/blob/ae54c7d525e94040cf8696d05f18d5e6f7d34012/searx/engines/ahmia.py#L21

so the engine is enabled only if SearXNG is connected to Tor.

2022-11-07 05:36 UTC, BoxingOctopus commented
> On the [wikipedia page](https://en.wikipedia.org/wiki/Z-Library), there are two onion URL.
> 
> Also, the category should be changed to onions like the ahmia engine:
> 
> https://github.com/searxng/searxng/blob/ae54c7d525e94040cf8696d05f18d5e6f7d34012/searx/engines/ahmia.py#L21
> 
> so the engine is enabled only if SearXNG is connected to Tor.

Done. Additionally, I've commented out the engine in `settings.yml`

2022-11-09 08:23 UTC, ghost commented
@BoxingOctopus maybe we can also replace the previous urls with the onion url in zlibrary.py?
[bookszlib​b74ugqojhzhg​2a63w5i2atv5bqarul​gczawnbmsb6s6qead.onion](url)

2022-11-09 18:02 UTC, BoxingOctopus commented
> @BoxingOctopus maybe we can also replace the previous urls with the onion url in zlibrary.py? [bookszlib​b74ugqojhzhg​2a63w5i2atv5bqarul​gczawnbmsb6s6qead.onion](url)

Done. 😃

2022-11-09 19:07 UTC, Evhorizon commented
> > @BoxingOctopus maybe we can also replace the previous urls with the onion url in zlibrary.py? [bookszlib​b74ugqojhzhg​2a63w5i2atv5bqarul​gczawnbmsb6s6qead.onion](url)
> 
> Done. 😃

Great 😉maybe checks are failing because of a misaligned indentation of the last lines?

2022-11-09 19:40 UTC, Evhorizon requested changes
Afaik the onion url should be http and not https

2022-11-09 20:47 UTC, Evhorizon commented
Opss maybe all this hard work is useless, the onion url points to a login page 😲

2022-11-09 20:59 UTC, Evhorizon requested changes
Try leaving all the engines section as it is and starting the settings.yml as follows:
```
use_default_settings:
  engines:
    remove:
      - z-library 
```

2022-11-09 23:33 UTC, Evhorizon requested changes
At this point i think that changes in zlibrary.py should be reverted, we should not want to add onion urls any more.

2022-11-09 23:41 UTC, BoxingOctopus commented
> At this point i think that changes in zlibrary.py should be reverted, we should not want to add onion urls any more.

Would it make more sense to just remove support for Z-Library entirely? It's not like this is a problem that's going to self-correct any time soon.

2022-11-09 23:48 UTC, ghost commented
> > At this point i think that changes in zlibrary.py should be reverted, we should not want to add onion urls any more.
> 
> Would it make more sense to just remove support for Z-Library entirely? It's not like this is a problem that's going to self-correct any time soon.

Yes, i think it's the faster and better solution, we could re-add the support just in case the service is back.

2022-11-10 00:05 UTC, BoxingOctopus commented
> > > At this point i think that changes in zlibrary.py should be reverted, we should not want to add onion urls any more.
> > 
> > 
> > Would it make more sense to just remove support for Z-Library entirely? It's not like this is a problem that's going to self-correct any time soon.
> 
> Yes, i think it's the faster and better solution, we could re-add the support just in case the service is back.

Alrighty then! Z-Library support has been zapped. 😄

2022-11-10 00:12 UTC, Evhorizon approved these changes

2022-11-10 06:31 UTC, Evhorizon commented
> 

Yeah! Hopefully this will be merged at last 😁

2022-11-10 08:07 UTC, tiekoetter commented
Hi can you please squash your commits together so each commit represents a significant change from the previous. Please also make sure to drop the ones not doing anything for the final outcome.

2022-11-10 08:14 UTC, Evhorizon commented
@BoxingOctopus i think that you can safely drop all the commits but the last one 😊

2022-11-10 19:13 UTC, return42 commented
FYI: this PR will also fix ..

```
ERROR   searx.engines.z-library       : Fail to initialize
Traceback (most recent call last):
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/share/searxng/local/py3/lib/python3.8/site-packages/anyio/_core/_sockets.py", line 218, in connect_tcp
    await event.wait()
  File "/share/searxng/local/py3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/share/searxng/local/py3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 733, in task_done
    exc = _task.exception()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/share/searxng/local/py3/lib/python3.8/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpcore/backends/auto.py", line 23, in connect_tcp
    return await self._backend.connect_tcp(
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share/searxng/searx/search/processors/abstract.py", line 75, in initialize
    self.engine.init(get_engine_from_settings(self.engine_name))
  File "/share/searxng/searx/engines/zlibrary.py", line 39, in init
    resp = http_get('https://z-lib.org', timeout=5.0)
  File "/share/searxng/searx/network/__init__.py", line 165, in get
    return request('get', url, **kwargs)
  File "/share/searxng/searx/network/__init__.py", line 96, in request
    return future.result(timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/share/searxng/searx/network/network.py", line 291, in request
    return await self.call_client(False, method, url, **kwargs)
  File "/share/searxng/searx/network/network.py", line 287, in call_client
    raise e
  File "/share/searxng/searx/network/network.py", line 272, in call_client
    response = await client.request(method, url, **kwargs)
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpx/_client.py", line 1513, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpx/_client.py", line 1600, in send
    response = await self._send_handling_auth(
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpx/_client.py", line 1702, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
```

2022-11-10 20:24 UTC, return42 commented
@BoxingOctopus thanks for your PR .. I modified your branch / I think we should leave the source untouched and just disabling the z-lib in the settings .. may be there comes the day we have z-lib back, then we have less work to enable it in SearXNG again.

2022-11-10 20:25 UTC, BoxingOctopus commented
> @BoxingOctopus thanks for your PR .. I modified your branch / I think we should leave the source untouched and just disabling the z-lib in the settings .. may be there comes the day we have z-lib back, then we have less work to enable it in SearXNG again.

Fine by me, I just want this thing working again without having to mess with configs. 😉

2022-11-10 20:29 UTC, merged