Correct a small mistake
searxng/searxng pull request #2074
Opened 2023-01-04 12:42 UTC by julianfairfax

## What does this PR do?

This corrects a small mistake in the docs

## Why is this change important?

It's not, but there's no reason not to make the change.

## How to test this PR locally?

I don't think you have to?

## Author's checklist

No notes

## Related issues

No issues for this are open as far as I know.

2023-01-04 18:26 UTC, return42 requested changes
Thanks for your patch / I have a nit to remark

2023-01-04 18:26 UTC, return42 commented on docs/src/index.rst
> +This is a partial documentation of our source code. We are not aiming to document
The double space after the dot of sentence end was intended. Typographic tools use the two spaces after the end of a sentence to distinguish from the period of an abbreviation.

2023-01-04 19:08 UTC, julianfairfax commented on docs/src/index.rst
> +This is a partial documentation of our source code. We are not aiming to document
Oh oops, that's my mistake. Fixed.

2023-01-05 06:19 UTC, return42 approved these changes
Thanks!

2023-01-05 06:19 UTC, merged