Added a check to see if the element contains links
searxng/searxng pull request #2089
Opened 2023-01-08 18:42 UTC by ahmad-alkadri

## What does this PR do?

Add a simple conditional `if` to check first if each search elements contain a link before proceeding to process that element. This fixes the `IndexError` caused by some elements in Bing search results not containing any links.

## Why is this change important?

Following [this fix](https://github.com/searxng/searxng/commit/9ee99423fe22550ef566245ef23e2a9e8ee76c27), specifically this line: 

https://github.com/searxng/searxng/blob/4e735b289b2a71583664e214e45aafccd0b85bfc/searx/engines/bing.py#L87

An Issue (#2087) was raised wherein Bing search results would include some elements that do not contain any link. This would cause the follow-up processes to crash, specifically on this line: 

https://github.com/searxng/searxng/blob/4e735b289b2a71583664e214e45aafccd0b85bfc/searx/engines/bing.py#L89

because it would expect a link element from the list but instead, it encountered an empty list. To prevent this, a simple conditional is thus added to check if the list is empty or not.

## How to test this PR locally?

Pull the branch with the latest commit of this PR locally, then run `make run`.

Alternatively, build a docker image locally and run it:

```docker
docker build -t $IMGNAME -f Dockerfile .
docker run -p $PORT:$PORT $IMGNAME:latest
```

Then do some searches using !bi flag, especially these two queries from which the Issue was raised:

`!bi certbot`
`!bi current events`

## Author's checklist

## Related issues

Closes #2087

2023-01-08 18:59 UTC, return42 requested changes
Thanks a lot for your work on this issue. Instead of indenting the entire loop I recommend a `continue`:

```
for .. in ..:
    link = eval_xpath(result, './/h2/a')
    if not link:
        continue
    link = link[0]
```

2023-01-08 19:13 UTC, ahmad-alkadri commented
> Thanks a lot for your work on this issue. Instead of indenting the entire loop I recommend a `continue`:
> 
> ```python
> for .. in ..:
>     link = eval_xpath(result, './/h2/a')
>     if not link:
>         continue
>     link = link[0]
> ```
> 
> 

Thanks for your input @return42. That makes sense, I can add those changes. I'd like to propose additional check though, specifically on the `link` object:

```python
for .. in ..:
     link = eval_xpath(result, './/h2/a')
     if not link:
         continue
     if len(link) == 0:
         continue
     link = link[0]
```

Just to be safe in case we got an empty list. What do you think?

2023-01-09 00:09 UTC, dalf commented
```python
link = eval_xpath_getindex(result, './/h2/a', 0, )
if link is None:
    continue
```
should work too.

2023-01-09 07:49 UTC, ahmad-alkadri commented
> ```python
> link = eval_xpath_getindex(result, './/h2/a', 0, None)
> if link is None:
>     continue
> ```
> 
> should work too.

@dalf @return42 That seems good. Would both of you prefer to use it? I'd be able to modify it quickly and push it to this PR this morning if you'd like. Thanks.

2023-01-09 07:52 UTC, return42 commented
@ahmad-alkadri : The suggestion of @dalf is a bit more elegant than mine, if you want you can use that.

2023-01-09 08:13 UTC, ahmad-alkadri commented
> @ahmad-alkadri : The suggestion of @dalf is a bit more elegant than mine, if you want you can use that.

@return42 @dalf. Okay, thank you. To be completely honest with you two I didn't even know that function exists before. I'll implement it ASAP, push it and keep you two updated once it's done.

2023-01-09 08:58 UTC, ahmad-alkadri commented
Did the push; could you please verify it @dalf @return42? Thanks in advance.

2023-01-09 14:17 UTC, return42 approved these changes
@ahmad-alkadri I rebased and slightly modified your patch and force pushed it on your branch / I have done it to shorten up "complicated things" / I hope this is OK

When I was in testing of this PR I realized, that we can't longer use the enumerate expression when we skip results / from the enumerate expression I made a simple counter that is incremented whenever a result item is added to the result list (but not when we skip an entry).  Further I thought it is better to make the XPath selector of the result loop more expressive.

I tried to explain it in the commit message --> 7fc8d72  .. my english is not the best, hope other can understand what I mean :-)

2023-01-09 14:17 UTC, merged

2023-01-09 22:29 UTC, ahmad-alkadri commented
> When I was in testing of this PR I realized, that we can't longer use the enumerate expression when we skip results / from the enumerate expression I made a simple counter that is incremented whenever a result item is added to the result list (but not when we skip an entry). Further I thought it is better to make the XPath selector of the result loop more expressive.
> 
> I tried to explain it in the commit message --> [7fc8d72](https://github.com/searxng/searxng/commit/7fc8d72889742399abb0d327e355ab350ddb395b) .. my english is not the best, hope other can understand what I mean :-)

@return42 I finally saw the changes that you made and they look great to me! Thanks for working on this with me tbh I learned a lot. Really appreciate it.