add option to change yacy search mode
searxng/searxng pull request #2587
Opened 2023-08-02 09:15 UTC by zutto

## What does this PR do?

Removes hardcoded "global" mode from Yacy engine and gives user an option to change the scope of the search instead.

## Why is this change important?

Yacy has two search modes, peer-to-peer search and local peer search. This PR enables the mode to be changed in the configuration.

`search_mode='global'` Does the peer-to-peer network search. This is the default search mode in Yacy.
`search_mode='local'` Does local peer only search.

In Yacy's default UI, this option is basically the top left "peer-to-peer" and "privacy" toggle.
![image](https://github.com/searxng/searxng/assets/4032653/71879bbd-0eed-442c-9e1e-6567fdf4237c)
And sometimes it's called Stealth Mode, because why not :grin:.
![image](https://github.com/searxng/searxng/assets/4032653/1cb1a419-bca2-4b25-8341-b33c47e1648c)

Documentation for reference https://wiki.yacy.net/index.php/Dev:APIyacysearch

2023-08-02 09:31 UTC, zutto commented
Also found this, looks like someone else has also made this same change earlier. https://github.com/searxng/searxng/issues/855

2023-08-02 09:53 UTC, return42 requested changes
Please fix the bugs reported by CI / I recommend to read [Development Quickstart](https://docs.searxng.org/dev/quickstart.html#development-quickstart).

`make format.python` should do the trick

2023-08-02 11:38 UTC, zutto commented
done

2023-08-03 17:57 UTC, return42 commented
Hi @zutto, thanks a lot for your PR, I squashed your two commits and added a 4fb14cd64 for a documentation.

Yacy sounds interesting, sadly the development stopped in 2016 / last release is [1.92](https://github.com/yacy/yacy_search_server/releases/tag/Release_1.92)

2023-08-03 17:58 UTC, merged