[feat] implementation of presearch engine (general, images, videos, news)
searxng/searxng pull request #2769
Opened 2023-09-14 12:47 UTC by Bnyro

## What does this PR do?
* implement the presearch engine (htttps://presearch.com)

## How to test this PR locally?
* !ps foo
* !psimg foo
* !psvid foo
* !psnews foo

## Known limitations
* the engine automatically picks the node to use based on the server location
* the specified time range is only supported for general results

## Related issues
closes #1939

2023-09-15 17:49 UTC, return42 commented
FYI: just rebased and removed a leftover [diff](https://github.com/searxng/searxng/compare/611142446b73ddff3ea6a8c60e8ba986f007b72c..cdc059c4ede4098e1d526708955ae0997414b9d5) .. still in review ..

2023-09-19 19:45 UTC, return42 commented
@Bnyro do we have any chance to add a language or at least a region support?

2023-09-19 20:13 UTC, Bnyro commented
> @Bnyro do we have any chance to add a language or at least a region support?
>

I've really been trying to figure that out.
Presearch works differently than other engines:
The language of the results depends on the node that we use, they have nodes everywhere across the world.

I just neither have been able to figure out a way to:
- get a list of all nodes and their regions/language code of the country
- set the location properly

My findings:
- You can search for locations via something like https://api.presearch.com/search-location?location=germ
- When you set the location, the `search_results_location` Cookie will be set, for Germ, France, it would be `JTdCJTIyZm9ybWF0dGVkJTIyJTNBJTIyNjUyNDAlMjBHZXJtJTJDJTIwRnJhbmNlJTIyJTJDJTIybGF0JTIyJTNBJTIyNDIuNzklMjIlMkMlMjJsb24lMjIlM0ElMjIwLjQzJTIyJTdE` -> No clue how that's related to the response of the location search link pasted above.

2023-09-19 20:17 UTC, Bnyro commented
From https://presearch.com/assets/app.js:
```
saveLocation:function(t,e){if(t){var n=s({},t),o=JSON.stringify(n),r=btoa(encodeURIComponent(o));i.default.set("search_results_location",r,a),this.state.savedLocation=n,this.hideInput(e),window.location.reload()}}
```

2023-10-04 13:10 UTC, return42 commented
@Bnyro I placed a commit on top of your branch to improve the implementation .. videos can't be shown by SearXNG's `video.html` template ..  see hint in module's doc-string.

After playing a while with this engine I think the results are not worth to investigate a lot more work / may I did already to much  .. anyway, I think the engine is worth to merge :+1: 

Can you have a final look, before we merge / thanks!

2023-10-05 08:03 UTC, Bnyro commented
> @Bnyro I placed a commit on top of your branch to improve the implementation .. videos can't be shown by SearXNG's `video.html` template .. see hint in module's doc-string.
> 
Neat, I've tested this for some time now and couldn't find any issues :+1:
The infobox works well too, I didn't even know presearch has support for it ...

> After playing a while with this engine I think the results are not worth to investigate a lot more work / may I did already to much .. anyway, I think the engine is worth to merge 👍
> 
I agree. Couldn't find any issues, ready to merge from my side! Thanks for your investigations :)

2023-11-03 16:00 UTC, unixfox commented
Good except no description for presearch videos:
![image](https://github.com/searxng/searxng/assets/4016501/f98e70b8-3f4a-46bb-aba6-75f5b06dff9c)

2023-11-03 16:09 UTC, Bnyro commented
Yes, presearch video results don't have any description unfortunately. E.g. https://presearch.com/videos?q=hey

2023-11-27 12:49 UTC, return42 approved these changes
> I agree. Couldn't find any issues, ready to merge from my side! Thanks for your investigations :)

Thanks / approved :+1:

2023-11-27 12:57 UTC, unixfox requested changes

2023-11-27 12:57 UTC, unixfox commented on searx/settings.yml
> +  - name: presearch
Could you make it so presearch is disabled by default?

We haven't discussed to add more engines by default.

2023-11-27 13:06 UTC, return42 commented on searx/settings.yml
> +  - name: presearch
good point .. did it https://github.com/searxng/searxng/compare/7ee74452fb8957a9859d9cad961615d8b4bb767c..845778b0c82525a0eca8dbaf6ed298083337fe1c

2023-11-27 13:16 UTC, unixfox approved these changes

2023-11-27 13:16 UTC, merged