Convert plugin searx.plugin.limiter to normal code
searxng/searxng pull request #2882
Opened 2023-09-29 10:36 UTC by dalf

## What does this PR do?

The limiter plugin is not a plugin:
* the user can't enable or disable the plugin and there is no point to allow that
* the limiter does use any of the features provides by the plugin framework

This commit convert the limiter plugin into normal code

Additional change: in `/config`, `limiter.enabled` is `true` only if the limiter is really enabled (Redis is available).

## Why is this change important?

The limiter is show as a plugin here and there and this is confusing.

## How to test this PR locally?

* check the app works without the limiter, check `/config`
* check the app works with the limiter and with the token, check `/config`

## Author's checklist

This feature has two names:
* limiter
* `searx.botdetection`

Since limiter is know name, in another PR, I suggest to rename `searx.botdetection` into `searx.limiter`. Actually some code already does that.

## Related issues

2023-09-29 11:06 UTC, return42 requested changes
Haven't tested .. but left some comments in the code to make it a little bit more readable .. what do you think?

2023-09-29 11:06 UTC, return42 commented on searx/botdetection/install.py
> +    return _INSTALLED
Do we need this indirection? .. isn't it simpler to use `botdetection.install.INSTALLED` in line 1295 of webapp.py?

2023-09-29 11:06 UTC, return42 commented on searx/webapp.py
> +)
Alias names make it hard to read the code .. instead of lasias names I prefer to import the module name:

    from searx import botdetection

.. and replace the usage of `link_token` by `botdetection.link_token` ...

2023-09-29 11:06 UTC, return42 commented on searx/webapp.py
> +                'enabled': botdetection_is_installed(),
here we can use `botdetection.INSTALLED`

2023-09-29 11:06 UTC, return42 commented on searx/botdetection/install.py
> +_INSTALLED = False
I would prefer `INSTALLED` .. see my comments below.

2023-09-29 11:08 UTC, dalf commented on searx/webapp.py
> +)
Either we change all these function names or we keep these alias for now, and make the change in another PR:
https://github.com/searxng/searxng/blob/26fed56d5149e8b56afaa4ecd4dd10332c8900df/searx/webapp.py#L1320-L1324

2023-09-29 11:10 UTC, dalf commented on searx/botdetection/install.py
> +    return _INSTALLED
It is written following redisdb code:
https://github.com/searxng/searxng/blob/26fed56d5149e8b56afaa4ecd4dd10332c8900df/searx/redisdb.py#L36-L37

2023-09-29 11:12 UTC, return42 commented
> Additional change: in `/config`, `limiter.enabled` is `true` only if the limiter is really enabled (Redis is available).

You now, that the limiter can be enabled without redis? .. the methods that [probe HTTP headers](https://docs.searxng.org/admin/searx.botdetection.html#module-searx.botdetection.http_accept) do not need a redis.

2023-09-29 11:16 UTC, return42 commented on searx/webapp.py
> +)
> and make the change in another PR

Is Ok for me .. we can do it in a code review.

2023-09-29 11:16 UTC, dalf commented
> (Redis is available)

This is misleading, the variable is True only when the limiter is actually installed (Redis installed or not).

https://github.com/searxng/searxng/blob/bee313c61c63aaa42ae859d3fa53041a2d1e67b4/searx/botdetection/install.py#L29-L43

You can see that `_INSTALLED = True` is done at the end after the hook is installed.

2023-09-29 12:48 UTC, dalf commented
For information the commit https://github.com/searxng/searxng/commit/c5baf9bfa1d1baf7d370929a4afca903e2e61eae applied on top of this PR move `searx.botdetection` to `searx.limiter`. 
@return42 if you think that make sense, I can add this commit to this PR.

2023-09-29 12:53 UTC, return42 commented
> if you think that make sense, I can add this commit to this PR.

not sure .. there are also some title or chapter naming that might be better changed from "botdetection" to "limiter" .. lets focus on the code in this PR .. and in a follow up we can discuss how to reorder the documentation.

2023-09-30 08:43 UTC, return42 commented
> There are two names to reference the same thing:
>
>    limiter
>    searx.botdetection
>
> Is there a difference between the botdetection and the limiter ?

In the past we had said the limiter is a simple builtin that limits request from an IP.  My intention was real *bot-detection* as an (optional) addition to the builtin limiter.  

The `searx.botdetection` namespace has not much (none except redis?) dependency to the rest of the SearXNG core .. As far as possible, I also don't want to bury bot detection too deep in the SearXNG code.  

Bot detection is a task that has nothing to do with the core of SearXNG, this should also be clearly visible on namespace level.  The "module" botdetection should in principle be interchangeable and the limiter is the integration in SearXNG. 

The modularization of limiter and botdetection should keep the possibility open for us to integrate external modules or components into the limiter in the future.

The only thing that would be missing at the moment is the definition of an interface between the limiter and the (external) bot detection.  The currently existing modularization in the code would make this very easy.  If we now merge the limiter with the botdetection this will not be so easy in the future.

TL;DR; just imagine that today's namespace `searx.botdetection` is an external module that you can install.

--> this is also the reason why this module has its own configuration .. 

:thinking: OK we can discuss if `limiter.toml` was a well chosen name :)

2023-09-30 09:59 UTC, dalf commented
So the name is `botdetection` not `limiter`.
However, everything outside this module is named `limiter`: the configuration options, configuration file, the API, etc...

There is no need to solve this in this PR: the purpose is just to remove the plugin [*] does not make sense.

[*] plugin as they are defined now.

2023-10-02 15:31 UTC, return42 commented on searx/botdetection/install.py
> +        return
This and what the undocumented `is_installed()` returns is unclear to me.

Does it mean `is_installed()` returns true only when redis is available and `settings['server']['public_instance']` is set to `true`?

Sorry, but this option `public_instance` only causes confusion, how is a developer supposed to understand this code without getting all the undocumented background to it?

2023-10-02 16:00 UTC, dalf commented on searx/botdetection/install.py
> +        return
Please Markus, is it possible for you to deal with choice that are not yours, like others do?
Yesterday, you said you want to do your PR, then switch back to my PR when I suggest to create myself a package for botdetection. The underlying question was not what to do, but the fact you want to ownership of the code. This is exhausting, and what remains in mind my mind is the fact that SearXNG is a playground and want to do whatever you want.

2023-10-03 04:31 UTC, dalf commented
Supersede by https://github.com/searxng/searxng/pull/2894

2023-10-03 04:31 UTC, closed without merging