[mod] add option max_page
searxng/searxng pull request #3002
Opened 2023-11-13 18:16 UTC by return42

Adds new option max_page and set the value of the google engines to 50

Related: https://github.com/searxng/searxng/issues/2982
Closes: https://github.com/searxng/searxng/issues/2972

2023-11-14 16:52 UTC, unixfox requested changes

2023-11-14 16:52 UTC, unixfox commented on searx/engines/brave.py
> +max_page = 6
I can request up to 9 pages on brave: https://search.brave.com/search?q=the&offset=8&spellcheck=0

Could you set max page to 10 instead?

related: https://github.com/searxng/searxng/issues/2982#issuecomment-1810679732

2023-11-14 16:52 UTC, unixfox commented on searx/engines/startpage.py
> +max_page = 9
I can request up to 18 pages on startpage: https://www.startpage.com/sp/search?query=the&cat=web
related: https://github.com/searxng/searxng/issues/2982#issuecomment-1810679732

could you set to max 20 pages just to be safe?

2023-11-14 16:54 UTC, unixfox commented
Thank you for the PR markus, really appreciate.

Hopefully we can have a max number of pages implemented for most of the major engines. I'll continue to do my findings in https://github.com/searxng/searxng/issues/2982

2023-11-14 17:03 UTC, return42 commented
> Thank you for the PR markus, really appreciate.

:+1: .. BTW fixed the `max_page` as you suggested.

> I'll continue to do my findings

:+1: .. but I think we can merge this PR after your review / to get the google bug fixed (https://github.com/searxng/searxng/issues/2972)

2023-11-14 17:06 UTC, unixfox commented
> 👍 .. but I think we can merge this PR after your review / to get the google bug fixed (#2972)

Yes I did not explicitly say in this PR.

2023-11-14 17:16 UTC, unixfox approved these changes

2023-11-14 20:03 UTC, Bnyro approved these changes
Pretty good solution for the issue if you ask me.

Thank you!

2023-11-14 20:05 UTC, dalf commented on searx/engines/brave.py
> +"""
There is a contradiction between these two values: 
* `paging=False`
* `max_page=10`.

Or did I miss something?

2023-11-14 20:06 UTC, dalf commented on searx/settings_defaults.py
> +        'max_page': SettingsValue(int, 0),
This default value should be in `settings.yml` too.

2023-11-14 20:08 UTC, dalf commented on searx/search/processors/abstract.py
> +            return None
Nitpicking: is it possible to group the two tests about `search_query.pageno` together so it is easy to see there are two tests about search_query.pageno ? (basically just move lines 157 - 160 above line 153).
Nitpicking...

2023-11-14 20:19 UTC, dalf commented
I feel the engine settings `paging` is superseded by `max_page` especially if the default value for `max_page` is 0 (as described in `settings_default.py`). For example:
* `max_page=0` means there is no paging (I'm not sure if the page starts counting at 0 or 1?).
* `paging=True` and `max_page=10` means ten pages are supported, but `paging=True` is useless.

==>

A suggestion:
* remove all `paging=True` in the engine, keep only `max_page`.
* as a safety net, `searx/engines/__init__.py` can set `paging=True` for engines which have `max_page > 0`.
* optional: replace easy to do checks about `engine.paging` like here: https://github.com/searxng/searxng/blob/b3d29cb86db4cc1a4e6320016529d1361451e1f1/searx/webapp.py#L1256

If we don't do that, does it make sense to add a check about invalid settings like `paging=False` and `max_page=10`?

2023-11-27 12:46 UTC, unixfox commented
@return42 did you had time to look at the comments of @dalf :)?

2023-11-27 13:01 UTC, return42 commented
> @return42 did you had time to look at the comments of @dalf :)?

Yes but to make it perfect it needs to touch a lot of files .. what will needs lot of tests .. all in all its becomes a "bigger" change and it will take its time .. nothing I can do at the moment (I'm in review of https://github.com/searxng/searxng/pull/2685 what is also a "big" change).

What I would suggest: To have a bugfix for https://github.com/searxng/searxng/issues/2972 we can merge this PR and do the big-change in a follow up PR?

2023-11-29 15:41 UTC, unixfox commented
I don't fully understand everything but wouldn't it be possible to at least implement the most important things that @dalf talked about in https://github.com/searxng/searxng/pull/3002#issuecomment-1811183122?
For the less important ones we can look at it later.

I know this PR is important, but I don't want to merge something that is not adequate and never look at it again, staying like this forever. And for the next one that read this new change, he gets confused in how it is implemented.

2023-11-29 15:58 UTC, return42 commented
> I don't fully understand everything but wouldn't it be possible to at least implement the most important things that @dalf talked about in https://github.com/searxng/searxng/pull/3002#issuecomment-1811183122?

In current master branch a engine has one option related to pages:

```python
paging = True
```

with this PR there comes another option related to pages

```python
max_page = 200
``` 

The pro side of this additional option is, that we have only to patch engines where we want to add a page limit.

@dalf suggested to remove ``paging`` option from all engines --> if an engines supports paging, its enough to define a `max_page`, where `max_page=0` is what `paging=False` today (unlimited pages) .. and if max_page is -1 (?) we have page support without a page limit.

The pro side is, that we do not have two options with an overlapping functionality / the con side is, we need some downward compatible code in the core and we have to touch all engines we have.

--> all in all its becomes a "bigger" task / I don't have time for.

2023-12-01 15:58 UTC, unixfox approved these changes
I'm ok with the changes if the refactor is too complex and large to do.

2023-12-02 08:21 UTC, return42 commented on searx/engines/brave.py
> +"""
This py-module is used for brave (web), brave.video and more brave engines .. only brave (web) supports paging.  By default paging is set to False and for brave (web) its activated in the [settings](https://docs.searxng.org/dev/engines/online/brave.html) .. 

We could discuss moving max_page for brave (web) to the settings as well.  But we could not add a doc-string there, which would also be automatically included in the documentation / this is at least the reason why I decided to implemented the option here on the module level.

2023-12-02 08:35 UTC, return42 commented
@dalf I fixed the code according to your remarks / see additional commits on the branch

> I'm ok with the changes if the refactor is too complex and large to do.

I would like to leave the decision to @dalf, he has to decide how important this proposal is to him.  Or whether it will be taken up afterwards.  If we do it in this branch, then I would appreciate support in the form of patches applied on this feature branch :+1:

2023-12-02 09:12 UTC, dalf commented on searx/engines/brave.py
> +"""
> But we could not add a doc-string there

I don't understand why because the documentation will show the same apparent contradiction.

Actually, `paging=False` in the code and `paging: true` in the configuration are also misleading.

With OOP, we would have one abstract class, and 3 classes, and the configuration would be much cleaner.

Ok. I close this comment.

2023-12-02 09:15 UTC, dalf approved these changes
I still think the add a burden to future development of engines.
But okay

2023-12-03 12:47 UTC, return42 commented
> I still think the add a burden to future development of engines.

I won't disagree with that, but if we only have a compromise in the time available to us, that is still more than having no solution at all. I will merge the PR now to solve the bug in #2972  .. thanks for taking the time and pointing out what can be improved :+1:

2023-12-03 12:47 UTC, merged