[mod] Capitalize theme names/styles in theme.html view file
searxng/searxng pull request #3022
Opened 2023-11-21 22:39 UTC by obfuscated-loop

## What does this PR do?

This changes the text within the `preferences/theme.html` view file to capitalize both theme names/styles. The original issue stated engines should also be capitalized however I disagree as I think it's much more logical to leave them as-is due to many engines having capitalized letters across the entire name. Maybe it would be a good idea to link the engines to a 'text-kind' name using a dictionary?

## Why is this change important?

It's not an incredibly important PR by any means, but it also something I have noticed personally and is a little bit of an eyesore.

## How to test this PR locally?

Goto `Preferences > User Interface` and you will see the capitalized names within the two related selectors/dropdowns.

## Related issues

Closes #3014

2023-11-22 23:34 UTC, obfuscated-loop commented
You may have to leave this one til last to merge as it's wriggled its way into some of my other PRs

2023-11-27 10:47 UTC, return42 requested changes
Thanks for the PR / LGTM :+1: .. one nit I have:

In #3014 the opener also asked for "autocomplete" drop down box .. can you add this also to your PR / thanks!

2023-11-27 21:55 UTC, obfuscated-loop commented
> Thanks for the PR / LGTM 👍 .. one nit I have:
> 
> In #3014 the opener also asked for "autocomplete" drop down box .. can you add this also to your PR / thanks!

Hi, I left this out intentionally as I thought it makes a lot more sense to leave the engines all lowercase. Think about such engines as DuckDuckGo which engines' name is `duckduckgo` - it would display as `Duckduckgo`, I.E not grammatically correct. I can change it to capitalized if you really think it would look better but I personally think it would look a bit rough like this.

2023-11-28 05:04 UTC, return42 approved these changes

2023-11-28 10:58 UTC, unixfox approved these changes
don't have opinion on this, why not

2023-12-23 08:07 UTC, merged