[fix] logger per engine: make .logger is always initialized
searxng/searxng pull request #305
Opened 2021-09-09 15:28 UTC by dalf

## What does this PR do?
the openstreetmap engine imports code from the wikidata engine.
before this commit, specific code make sure to copy the logger variable to the wikidata engine.

with this commit `searx.engines.load_engine` makes sure the `logger` is initialized.
The implementation scans `sys.modules` for module name starting with `searx.engines`.

## Why is this change important?

Without this PR, `import searx.engines.an_engine` may not work:
* `searx.engines.an_engine.logger` won't be initialized
* as soon as code in `searx.engines.an_engine` makes a reference to `searx.engines.an_engine.logger` the engine crash.

With this PR, `searx.engines.load_engine` makes sure the .logger is initialized.

See the result of `git grep "from searx.engines"`

## How to test this PR locally?

* `!osm somewhere`

## Author's checklist

## Related issues

2021-09-10 06:57 UTC, return42 commented
> The name in sys.module is xpath without the prefix searx.engines

If so, I think the problem is not the initialization of the logger, the problem is that we have two copies of the engine module in the namespace of the runtime.

If I'm not wrong we have to fix ..

https://github.com/searxng/searxng/blob/1973e4ecf691f173299fb11abc61750009bdef84/searx/utils.py#L428-L438

The problem is, that  (e.g.) xpath is registered by `sys.modules['xpath'] = module` while the unique module name should be `sys.modules['searx.engines.xpath'] = module`

2021-09-10 08:42 UTC, dalf commented
> The problem is, that (e.g.) xpath is registered by sys.modules['xpath'] = module while the unique module name should be sys.modules['searx.engines.xpath'] = module

I've made a first implementation that does this, but I'm not sure this is what we want.
For example, searxng loads the module `searx.engines.xpath` many times: once per engine is settings.yml that uses the xpath engine. To sum up:

* The modules in `searx.engines.*` are like classes.
* The values of `searx.engines.engines` are instances.
* `searx.engines.load_engine` is the generic constructor.

From this, when ` from searx.engines.xpath import extract_text ` what should do?
* Import a random(*) instance ( `sys.modules['searx.engines.xpath'] = module` ). Random = the last engine declared in settings.yml
* Import the class (known state).

The later one works. So I think we can remove `sys.modules[modname] = module` from `load_module`.

2021-09-10 17:51 UTC, return42 commented
Sorry, I wasn't aware about `searx.engines.engines` .. and now I understand the problem :-)

> To sum up:
> * The modules in `searx.engines.*` are like classes.
> * The values of `searx.engines.engines` are instances.

Hm, from my point both are _module namespaces_ ....

`from searx.engines import xpath` imports module xpath and register this _module namespaces_ in the _global namespace of the loaded modules_

```
>>> from searx.engines import xpath
>>> xpath
<module 'searx.engines.xpath' from '/800GBPCIex4/share/searx/searx/engines/xpath.py'>
>>> sys.modules['searx.engines.xpath']
<module 'searx.engines.xpath' from '...../searx/searx/engines/xpath.py'>
```

while `load_module()` just returns a _module namespaces_

```
>>> load_engines(settings['engines'])['azlyrics']
<module 'xpath' from '/800GBPCIex4/share/searx/searx/engines/xpath.py'>
```

> So I think we can remove `sys.modules[modname] = module` from `load_module`.

Yes we should not register in `sys.modules` what is loaded by `load_module()`. Or with other words: only imported _module namespaces_   should be registered  in `sys.modules`, not those are loaded.

But the https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly is just mystic for me :) .. I do not know what the methods from `import.utils` do _behind the scene_.

2021-09-10 18:53 UTC, dalf commented
About `load_module`, see issue #312

2021-09-12 08:38 UTC, return42 commented on searx/engines/__init__.py
> +            module.logger = logger.getChild(module_engine_name)
I recommend to use parentheses ..

```diff
@@ -121,9 +121,10 @@ def set_loggers(engine, engine_name):
     # the engine may have load some other engines
     # may sure the logger is initialized
     for module_name, module in sys.modules.items():
-        if module_name.startswith('searx.engines') \
-            and module_name != 'searx.engines.__init__' \
-            and not hasattr(module, 'logger'):
+        if (module_name.startswith('searx.engines')
+            and module_name != 'searx.engines.__init__'
+            and not hasattr(module, 'logger')
+        ):
```

2021-09-12 08:43 UTC, return42 requested changes
I tried to test before and after this patch has applied ...

> Without this PR, `import searx.engines.an_engine` may not work:
> * `searx.engines.an_engine.logger` won't be initialized
> * as soon as code in `searx.engines.an_engine` makes a reference to `searx.engines.an_engine.logger` the engine crash.

.. sounds logical for me, but I can't reproduce a crash (before this patch is applied). I used `!osm paris` to test.

2021-09-12 10:12 UTC, dalf commented
The OSM engine has a workaround that is removed by this PR: 
https://github.com/searxng/searxng/blob/c3473480f4255a81d83ac48201e0702778398d23/searx/engines/openstreetmap.py#L443-L445

If you remove these lines, `!osm paris` doesn't work.

2021-09-13 06:48 UTC, dalf commented on searx/engines/__init__.py
> +            module.logger = logger.getChild(module_engine_name)
updated

2021-09-13 07:00 UTC, return42 approved these changes

2021-09-13 07:03 UTC, merged