[feat] engine: implementation of yandex music
searxng/searxng pull request #3234
Opened 2024-02-20 11:58 UTC by userXinos

## What does this PR do?

adds the yandex music engine

## Why is this change important?

russian streaming service of music

## How to test this PR locally?

- `!ydm test`

![изображение](https://github.com/searxng/searxng/assets/40886699/ce306664-9645-401b-9770-caf7f401fda8)

### note

I added an iframe similar to spotify, but it seems to be too big for the small media window

2024-02-20 15:32 UTC, return42 requested changes
@userXinos I had to modify some parts to pass the quality gate and pushed commit https://github.com/searxng/searxng/pull/3234/commits/4ef40483676127617e3b0b6fc367b80c93b9ae0d on you branch.

When I test the engine I most often get none results .. 

Search for `!ydm Nothing Else Matters` --> https://music.yandex.ru/handlers/music-search.jsx?text=q=Nothing+Else+Matters&type=track&page=1

Search for `!ydm Metallica` --> https://music.yandex.ru/handlers/music-search.jsx?text=q=Metallica&type=track&page=1

When I search same terms on https://music.yandex.ru/search?text=metallica I got a lot of results.

Are you sure the request is correct? When I use [`type=all`](https://music.yandex.ru/handlers/music-search.jsx?text=metallicax&type=all') I get the results I would expected ..

    curl 'https://music.yandex.ru/handlers/music-search.jsx?text=metallicax&type=all' > out.json ; firefox out.json

2024-02-20 16:06 UTC, userXinos commented
ohh...😓, 

if set type=all will need to create a separate design for each element (`track`, `artist`, `playlist`, `album`, `video`) probably ?

traks: https://music.yandex.ru/search?text=Nothing%20Else%20Matters&type=tracks&page=1
all (default frontend belabour) : https://music.yandex.ru/search?text=Nothing%20Else%20Matters

2024-02-21 06:46 UTC, return42 approved these changes
> if set type=all will need to create a separate design for each element (`track`, `artist`, `playlist`, `album`, `video`) probably ?

I think the new `track` you fixed gives us the results we expect :+1:

Since access to music is [limited to a few countries](https://yandex.com/support/music/access.html) I set this engine to `inactive: true`, to get in use of this engine in your SearXNG instance you have to set this option in your `/etc/searxng/settings.yml`

```yaml
engines:

    - name: yandex music
      inactive: false
```


Here you can see my modifications --> [diff](https://github.com/searxng/searxng/compare/55d63ebcef26020777666d943558085aba8f5100..7b2e4f7a73afebf30ebebe21239d6130a4bc62cd)

2024-02-21 08:28 UTC, Bnyro commented on searx/engines/yandex_music.py
> +    for result in search_res.get('tracks', []).get('items', []):
This will certainly throw an exception, because we would try to index a list with a key? It probably should be `search_res.get('tracks', {})`, ...

2024-02-21 08:29 UTC, Bnyro commented on searx/engines/yandex_music.py
> +    # return results
Please remove that line

2024-02-21 08:30 UTC, Bnyro commented on searx/engines/yandex_music.py
> +                    'url': '{}/album/{}/track/{}'.format(url, album_id, track_id),
```suggestion
                    'url': f'{url}/album/{album_id}/track/{track_id}',
```

2024-02-21 08:31 UTC, Bnyro commented on searx/engines/yandex_music.py
> +                    'url': '{}/album/{}/track/{}'.format(url, album_id, track_id),
Please use `f` strings where possible, also for `content` and `iframe_src`

2024-02-21 08:33 UTC, return42 commented
@userXinos it seems my review was a bit sloppy .. if it is OK for you, I will fix the issues repoted by @Bnyro in a second review ..

2024-02-21 08:33 UTC, Bnyro commented on searx/engines/yandex_music.py
> +    params['url'] = search_url.format(query=urlencode({'text': query}), page=params['pageno'] - 1)
```suggestion
    args = {'text': query, 'page': params['pageno'] - 1}
    params['url'] = search_url + urlencode(args)
```

2024-02-21 08:34 UTC, userXinos commented
no problem, I'll fix the problems now

2024-02-21 08:34 UTC, Bnyro commented on searx/engines/yandex_music.py
> +search_url = url + '/handlers/music-search.jsx?{query}&type=track&page={page}'
```suggestion
search_url = url + '/handlers/music-search.jsx?type=track&'
```

2024-02-21 08:44 UTC, Bnyro approved these changes

2024-02-21 16:12 UTC, return42 approved these changes
> no problem, I'll fix the problems now

you should test what you give to us for a review .. --> [Development Quickstart](https://docs.searxng.org/dev/quickstart.html#development-quickstart)

I had to [fix the URL](https://github.com/searxng/searxng/compare/2c2b10f0a782723aa3b4a06b582fc3bb848962c5..5374039) / otherwise I got a 404 from yandex and there was an issue with the f-string (didn't pass the `make test`).

2024-02-21 16:17 UTC, merged