[feat] gitea: implement dedicated module
searxng/searxng pull request #3468
Opened 2024-05-07 17:01 UTC by Bnyro

## What does this PR do?
- implement a module for gitea
- by default we only have a codeberg engine available (as before)

## Why is this change important?
- it provides more details than before
- see #3268

## How to test this PR locally?
- !cb foot
- !cb gadgetbridge

## Related issues
see #3268

2024-05-11 15:15 UTC, return42 requested changes
> implement a module for gitea

yeah having a gitea module is much better: developer can now search their local gitea instance .. in best quality .. :rocket:

To make it more clear in the commit history, we should split the commit into two; in the first add the python module and in the second move codeberg from XPath engine to gitea engine.

Can you please split the commit? .. afterwards I can squash some more documentation into the gitea module / thanks a lot!

2024-05-11 15:15 UTC, return42 commented on searx/engines/gitea.py
> +"""Github (IT)
C&P issue :)

2024-05-11 15:15 UTC, return42 commented on searx/engines/gitea.py
> +base_url = "https://codeberg.org"
Lets set default `base_url` to `None`  and add a [`init(..)`](https://docs.searxng.org/dev/engines/demo/demo_online.html#searx.engines.demo_online.init)  to check if base_url is configured in the engine settings.

2024-05-14 15:01 UTC, return42 approved these changes
FYI: I added the engine to the online docs / when merged into master available at: https://docs.searxng.org/dev/engines/online/gitea.html

2024-05-14 15:01 UTC, return42 commented on searx/settings.yml
> +    disabled: true
FYI: I added gitea.com to the first commit.

2024-05-14 18:33 UTC, Bnyro commented
> FYI: I added the engine to the online docs / when merged into master available at: https://docs.searxng.org/dev/engines/online/gitea.html
>
Thanks, looks good to me :+1:

2024-05-15 05:23 UTC, merged