cleanup: remove usage of gen_useragent in engines
searxng/searxng pull request #3559
Opened 2024-06-09 18:24 UTC by glanham-jr

## What does this PR do?

remove usage of gen_useragent in engines

## Why is this change important?

Reduce tech debt - clarify usage of `gen_useragent` not in engines

## How to test this PR locally?

n/a, ensure engines work as expected

## Author's checklist
n/a

## Related issues
context for changes [here](https://github.com/searxng/searxng/pull/3556#issuecomment-2156461261)

2024-06-09 19:05 UTC, Bnyro approved these changes

2024-06-10 06:06 UTC, return42 requested changes
> remove usage of gen_useragent in engines

We may only remove the header from the `request()` functions, only there it is superfluous for (online engines).  So only in the nojeek engine, in the other two places the header is used for another request, which is not automatically extended by the UA header.

2024-06-10 06:06 UTC, return42 commented on searx/engines/startpage.py
> -        'User-Agent': gen_useragent(),
Same here, don't remove it from the fetch traits function.

2024-06-10 06:06 UTC, return42 commented on searx/engines/presearch.py
> -        'User-Agent': gen_useragent(),
Don't remove UA from here, this header is used in the HTTP GET request in line 134.

2024-06-10 22:57 UTC, glanham-jr commented
Interesting, thanks for the context. I'll see if there is a good place to add that info.

2024-06-11 00:19 UTC, glanham-jr commented
@return42 Resolved comments + added unit tests regarding the default usage of `UserAgent`.

2024-06-17 13:27 UTC, return42 commented
> * Implement a unit test to validate that `gen_useragent` is provided by default for `online` processors

The tests are not executed .. move `tests/unit/search/processors/test_online.py` to `tests/unit/test_online_processor.py` and the tests will be executed.

If I do so and `make run` I got the following issues:

```
$ make test.unit
TEST      tests/unit
.......................EE.................................................................................WARNING searx.botdetection.config     : missing config file: /etc/searxng/limiter.toml
.............................................................
======================================================================
ERROR: test_get_params_default_params (tests.unit.test_online_processor.TestOnlineProcessor.test_get_params_default_params)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/800GBPCIex4/share/SearXNG/tests/unit/test_online_processor.py", line 27, in test_get_params_default_params
    online_processor = online.OnlineProcessor(TEST_ENGINE, TEST_ENGINE_NAME)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/800GBPCIex4/share/SearXNG/searx/search/processors/abstract.py", line 66, in __init__
    self.logger = engines[engine_name].logger
                  ~~~~~~~^^^^^^^^^^^^^
KeyError: 'dummy engine'

======================================================================
ERROR: test_get_params_has_gen_useragent (tests.unit.test_online_processor.TestOnlineProcessor.test_get_params_has_gen_useragent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/800GBPCIex4/share/SearXNG/tests/unit/test_online_processor.py", line 38, in test_get_params_has_gen_useragent
    online_processor = online.OnlineProcessor(TEST_ENGINE, TEST_ENGINE_NAME)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/800GBPCIex4/share/SearXNG/searx/search/processors/abstract.py", line 66, in __init__
    self.logger = engines[engine_name].logger
                  ~~~~~~~^^^^^^^^^^^^^
KeyError: 'dummy engine'

----------------------------------------------------------------------
Ran 167 tests in 4.859s
```

2024-06-22 17:15 UTC, glanham-jr commented
@return42 Did some research on python Mocking, updated the unit tests and its working now :smile:

2024-06-23 06:50 UTC, return42 commented
> updated the unit tests and its working now 😄

Please @glanham-jr ..  I can only repeat what I have written above:

The engine tests are not executed!! .. For the same reason you already fixed in:

- https://github.com/searxng/searxng/pull/3599

2024-06-23 09:51 UTC, return42 approved these changes
FYI I fixed the test --> [diff](https://github.com/searxng/searxng/compare/940c1167c907cf99f82fd3c0404b40b5adef0997..19ce430ac27c56ab28cbf9db66e47491e5105285)

2024-06-23 09:51 UTC, merged

2024-06-23 13:30 UTC, glanham-jr commented
I definitely had different changes that I pushed, and definitely had it fixed locally... apologies for the false ping, I should have double checked the changes were reflected in the PR.