Add a link to the libretranslate system
searxng/searxng pull request #3627
Opened 2024-06-29 10:46 UTC by cy8aer

This may help for further translations.

## What does this PR do?

This adds a link to the used libretranslate instance. It uses `from_lang`, `to_lang`, and `query` to transfer the translation parameters.

## Why is this change important?

This can be helpful to do further translations on the libretranslate instance.

## How to test this PR locally?

Search string: `!lt en-de this is a nice test` - will output the search string in the answer field (as before) and in addition the link to the instance.

## Author's checklist

-

## Related issues

-

2024-06-29 11:10 UTC, Bnyro requested changes
Please undo the formatting changes, they're not related to this PR.

2024-06-29 11:23 UTC, cy8aer commented
Rebased.

2024-06-29 18:42 UTC, cy8aer commented
Ok, pure patch now (without formatting) though I do not understand why the python CIs do not make problems now :-/

2024-06-30 06:34 UTC, return42 commented on searx/engines/libretranslate.py
> +                "url": "%s/?source=%s&target=%s&q=%s" % (base_url[0], from_lang, to_lang, origin),
`base_url` can be a list or a string / see line 24 in the request function.

2024-06-30 08:35 UTC, cy8aer commented
I now use the same mechanism like in the request: Get some random `base_url`  if it is a list, `base_url` else.

2024-06-30 11:21 UTC, cy8aer commented
Oups typo in description: random.choice!

2024-06-30 12:01 UTC, Bnyro commented
I think it'd be better to set `params['base_url']` in the `request` method and use that base url via `resp.search_params['base_url']` in the `response` method instead of picking an other instance, as the other instance might not be working. It's only safe to say that the instance used for the request did return a proper response and thus probably works.

2024-06-30 12:02 UTC, Bnyro commented on searx/engines/libretranslate.py
> +                "url": "%s/?source=%s&target=%s&q=%s" % (r_url, from_lang, to_lang, origin),
```suggestion
                "url": f"{base_url}/?source={from_lang}&target={to_lang}&q={query}",
```

2024-06-30 12:04 UTC, cy8aer commented
> I think it'd be better to set `params['base_url']` in the `request` method and use that base url via `resp.search_params['base_url']` in the `response` method instead of picking an other instance, as the other instance might not be working. It's only safe to say that the instance used for the request did return a proper response and thus probably works.

Oh, that makes more sense. I did not know that this persistence is possible.

2024-06-30 12:33 UTC, cy8aer commented
I had a typo in the new url and now rebased the whole stuff to clean up.

2024-06-30 14:18 UTC, Bnyro approved these changes
Thank you!

2024-06-30 14:18 UTC, merged