[mod] remove py 3.6 leftovers
searxng/searxng pull request #3642
Opened 2024-07-07 04:40 UTC by allendema

## What does this PR do?
Removes `uvloop`.

## Why is this change important?
Python 3.6 is not supported.

## How to test this PR locally?
 
- `make test` 
- `make run` 
- search `contrafibularities`.

## Author's checklist

Will this break anything? Because the above worked.
https://github.com/search?q=repo%3Asearxng%2Fsearxng%20uvloop&type=code

## Related issues
https://github.com/MagicStack/uvloop/pull/578

N/A

2024-07-07 06:03 UTC, return42 commented
> Will this break anything? Because the above worked.

No, not break, but AFAIK uvloop is optional and has been added in #1 for performance reasons .. @dalf should we remove uvloop?

2024-07-07 21:31 UTC, Bnyro approved these changes, later dismissed

2024-07-10 14:07 UTC, dalf commented
@allendema I don't follow the link between "remove py 3.6 leftovers" and uvloop?

uvloop 
* supports Python versions from [3.8 to 3.12](https://github.com/MagicStack/uvloop/blob/6c770dc3fbdd281d15c2ad46588c139696f9269c/pyproject.toml#L22-L26)
* makes [asyncio faster](https://github.com/MagicStack/uvloop?tab=readme-ov-file#performance). However, I haven't tested it for a long time.

2024-07-12 10:45 UTC, return42 requested changes
> @allendema I don't follow the link between "remove py 3.6 leftovers" and uvloop?

I think we simply forgot to remove the outer try / except block when 

- https://github.com/searxng/searxng/pull/646
- https://github.com/searxng/searxng/commit/cb1b6686f0c7f73ff4b8d4302921a4ca1a9db8c8

2024-07-12 10:45 UTC, return42 commented on requirements.txt
> -uvloop==0.19.0
Don't delete this requirement.

2024-07-12 10:45 UTC, return42 commented on searx/network/client.py
> -
remove the outer try / except block

```python
import uvloop
uvloop.install()
```

2024-07-13 12:31 UTC, return42 commented
FYI error in the CI tests is related to:

- https://github.com/searxng/searxng/issues/2988#issuecomment-2226816848

2024-07-13 15:20 UTC, merged

2024-07-13 15:34 UTC, allendema commented
@dalf: Yes, only the try / except needed to be removed.
Thanks @return42.