feat: Add torznab engine
searxng/searxng pull request #391
Opened 2021-10-07 00:46 UTC by paolobasso99

## What does this PR do?
Add a torznb engine.

## Why is this change important?
SearXNG already supports some torrent trackers.
Adding support for the torznab apis opens the possibility to use [Jackett](https://github.com/Jackett/Jackett) and [Prowlarr](https://github.com/Prowlarr/Prowlarr) to query a lot of public and private trackers.

## How to test this PR locally?

In order to test this PR locally it is needed to:

- install [Jackett](https://github.com/Jackett/Jackett)
- add a torrent tracker
- add the engine to `settings.yml` as:
  ```
  - name: jackett
    engine: torznab
    shortcut: jkt
    base_url: http://localhost:9117/api/v2.0/indexers/all/results/torznab
    enable_http: true # if using localhost
    api_key: xxxxxxxxxxxxxxxxx
  ```
- test the engine performing a file search

## Author's checklist

## Related issues
Closes #385 (created by me)

2021-10-07 09:30 UTC, return42 commented on searx/engines/torznab.py
> +        result["leech"] = get_torznab_attr(item, 'leechers')
I dont know why, but I never see 'leechers' in the XML, even if there are some .. e.g. this is the result from my jackett instance ..

![grafik](https://user-images.githubusercontent.com/554536/136356878-9f603e91-6539-40e5-9d97-27b5ef3fc195.png)

And this is the same result (except leechers) in SearXNG ..

![grafik](https://user-images.githubusercontent.com/554536/136356692-f086dcf4-1be3-4ae1-87f1-459a2a7ced9b.png)

I also checked the XML response on various queries but never see a `<torznab:attr name="leechers" value="..." />` tag.  May be there is something wrong in my Jackett instance?

2021-10-07 09:36 UTC, return42 commented on searx/settings.yml
> +#     - 5000
Do you know where we can get a full list of supported categories (numbers and meaning)?

2021-10-07 09:41 UTC, paolobasso99 commented on searx/settings.yml
> +#     - 5000
Yes
The categories supported by Jackett are: https://github.com/Jackett/Jackett/wiki/Jackett-Categories

2021-10-07 10:02 UTC, return42 requested changes
FYI: on top of your branch I pushed two commits with marginal fix / are these changes OK for you?

Beside the comment about _leechers_ I can't find any issue more.  Did _leechers_ work in your tests?

Thanks a lot for this PR!

2021-10-07 14:12 UTC, paolobasso99 commented
While the `leechers` attribute exists I think that Jackett just compute the number of leechers as `peers - seeds`.
I added a commit to reflect this behaviour when the attribute is missing.

2021-10-07 14:17 UTC, return42 commented
> I added a commit to reflect this behaviour when the attribute is missing.

Cewl .. thanks / that was what I also thought .. I will continue with my tests.  May be I squash some commits before merge.

Error handling works !

![grafik](https://user-images.githubusercontent.com/554536/136410172-39c9868d-70fc-47b7-8e08-792b52f10f0b.png)

2021-10-07 15:25 UTC, return42 approved these changes

2021-10-07 15:27 UTC, merged

2021-10-07 15:30 UTC, return42 commented
@paolobasso99 this was your first PR to SearXNG, excellent work I would say .. thanks a lot!!!

2021-10-07 15:35 UTC, paolobasso99 commented
Thanks!
I am using SearXNG as my main search engine now so if I will need some other engine/feature I will try to add it myself.

2021-10-07 15:54 UTC, return42 commented
> so if I will need some other engine/feature I will try to add it myself.

that's good .. we need contributors .. feel welcome :)

OT: you can now drop your [torznab_engine branch](https://github.com/paolobasso99/searxng/tree/torznab_engine)

2022-04-23 19:56 UTC, sbstratos79 commented
I have opened 2 issues about this engine. #1124 & #1125 
#1124 is especially important if somebody decides to use this to serve results from a private tracker as it could potentially lead to the instance owner's private tracker's account getting banned.