[mod] new preference: query_in_title
searxng/searxng pull request #485
Opened 2021-11-06 11:37 UTC by dalf

## What does this PR do?

* disable by default
* settings.yml: ui.query_in_title
* in /preferences: privacy tab

when enabled, the result page's title contains the user query.

previously:
* oscar theme: the query was always included
* simple theme: the query was included with the GET method

![image](https://user-images.githubusercontent.com/1594191/140608059-17d3c445-fcd8-4ebc-80cc-6cb62c4a5756.png)

![image](https://user-images.githubusercontent.com/1594191/140608065-27efb01a-556a-4ecd-8ecd-119bb1ba5c30.png)

## Why is this change important?

Some browser records the page history using the HTML title pages.

See https://github.com/searxng/searxng/issues/434#issuecomment-962023693

## How to test this PR locally?

With the simple and oscar themes:
* make a query : check there is NO title
* change the preferences: check there is a title
* reset the preferences
* in settings.yml: set `ui.query_in_title: true`
* check there is a title
* in settings.yml: set `lock: - query_in_title`
* `/preferences`: check the option has disappeared.

## Author's checklist

## Related issues

Related to #434

2021-11-06 20:43 UTC, MrPaulBlack requested changes
I suggest changing the line in results.html in both oscar and simple to (This way there is a space between the query and the `-` like so: `time - SearXNG`):

```html
{% block title %}{% if query_in_title %}{{ q|e }} - {% endif %}{% endblock %}
````

* :+1: enabeling the setting in pref. in oscar and simple works
* :+1: disabeling the setting in pref. in oscar and simple works
* :-1: enabeling query in title does NOT work through settings.yml (`query_in_title: true` in ui section; this is the case for both themes)
* :+1: locking the setting in settings.yml works for both themes

2021-11-07 07:55 UTC, dalf commented
> 👎 enabeling query in title does NOT work through settings.yml (query_in_title: true in ui section; this is the case for both themes)

Fixed.
Also, the values is stored in `query_in_title` (underscore) in settings, preferences and Jinja context (no mismatch with `query-in-title`).

@unixfox : the default value is off. So the title will disappear from page's title when the instances are upgraded unless the user explicitly set the value to on.

Possible better implementation: 
* set the default value to "on" for FF browser, "off" otherwise.
* in `settings.yml`: `query_in_title: auto` (`false`, `true` are still possible, `auto` is additional value)
* the function `searx.webapp.pre_request`  set the value according to the user agent (something similar is already for the HTTP method).

2021-11-07 09:35 UTC, dalf commented
`make test.robot` fails because of this line:
https://github.com/searxng/searxng/blob/49879a4a63652d638bce21d8cdf1da3d65415d3a/searx/templates/oscar/preferences.html#L289

More precisely, removing `{% if not query_in_title %}selected="selected"{% endif %}` from this line fixes this error:
```
Error occured: Traceback (most recent call last):
  File "/home/alexandre/code/searx/tests/robot/__main__.py", line 69, in main
    run_robot_tests([getattr(test_webapp, x) for x in dir(test_webapp) if x.startswith('test_')])
  File "/home/alexandre/code/searx/tests/robot/__main__.py", line 62, in run_robot_tests
    test(browser)
  File "/home/alexandre/code/searx/tests/robot/test_webapp.py", line 55, in test_preferences_engine_select
    assert browser.find_by_xpath('//input[@id="engine_general_dummy__general"]').first.checked
AssertionError
```

I can't figure out why.

Looking at the HTML page:
```
export SEARXNG_SETTINGS_PATH=$(pwd)/tests/robot/settings_robot.yml
make run
xdg-open http://localhost:11111
```
I don't see any issue.

2021-11-07 10:03 UTC, MrPaulBlack commented
Also: Setting anything it the settings on the user device through the /preferences endpoint does not work anymore. It seems the POST request when pressing the save btn does not work anymore:

![image](https://user-images.githubusercontent.com/38733246/140640565-c349f8ad-17fa-423c-9f76-a4c4c04d79ce.png)

2021-11-09 07:37 UTC, dalf commented
@MrPaulBlack the issue you describe is exactly why the tests fail : 
* the preferences are [saved](https://github.com/searxng/searxng/blob/90acb342d32b1ce890402acbc24cc9a5793fddc6/tests/robot/test_webapp.py#L46) : it fails silently.
* then code checks the preferences are [changed](https://github.com/searxng/searxng/blob/90acb342d32b1ce890402acbc24cc9a5793fddc6/tests/robot/test_webapp.py#L55)

I've added
https://github.com/searxng/searxng/blob/80fb77476fad4b229418c530f3ffda67f357a15a/searx/preferences.py#L409
(`image_proxy` preference definition has the "workaround")

So now it should work.

---

Perhaps with Firefox, the default value should be `true` and `false` in other cases.

2021-11-24 09:31 UTC, mrpaulblack commented
FYI: Firefox does actually log the page title in history

![image](https://user-images.githubusercontent.com/38733246/143211854-207c4674-da01-4fcb-80b6-cd83086dfdd6.png)

I think this setting should be off by default...

2021-11-24 09:34 UTC, dalf commented
> FYI: Firefox does actually log the page title in history

even wit the POST method ?

2021-11-24 09:42 UTC, mrpaulblack commented
Woow you are right; It does not log page title when using POST method with query in page title enabled mb...

2021-11-24 09:52 UTC, dalf commented
By default, for a Firefox user, this setting can be enabled when the method is POST, and disabled in all other cases.
It is doable but.... that's a mess from the user point of view: why suddenly the title has disappear? 

So as you said, it should be disabled by default.

There are an inconsistent settings:
* in the /preferences, it is in the privacy section.
* in `settings.yml`, the preferences in under the `ui` section (there is no privacy section).

2021-11-24 10:35 UTC, mrpaulblack approved these changes
I think the inconsistency in settings.yml is fine; since its the only privacy setting from the theme in settings.yml and still kinda fits into that category (if there are more privacy items we should probably think about adding the category to settings.yml...). I also retested and everything works now :+1: (settings.yml change in simple and oscar and also changing in /pref. in simple and oscar).... The only thing I would change is to add a space after the query and before the `-`:

![image](https://user-images.githubusercontent.com/38733246/143222338-1683520a-e94e-49ea-8c9d-4c1e88b62580.png)

(But dont know how and its not that important if not tbh)

2021-11-24 12:10 UTC, merged

2021-11-24 14:11 UTC, return42 commented on searx/templates/oscar/preferences.html
> +                        {% set query_in_title_info = _('When enabled, the result page\'s title contains your query. Your browser can record this title') %}
While I was in translation I recognized that we have this sentence twice, here in oscar (missing the final dot) and in simple (with a dot at the end).

2021-11-24 14:11 UTC, return42 commented on searx/templates/simple/preferences.html
> +      <div class="description">{{ _('When enabled, the result page\'s title contains your query. Your browser can record this title.') }}</div>
Here is a final dot.

2021-11-28 13:01 UTC, return42 commented on searx/templates/oscar/preferences.html
> +                        {% set query_in_title_info = _('When enabled, the result page\'s title contains your query. Your browser can record this title') %}
fixed in 3f3097c7

2021-11-28 13:01 UTC, return42 commented on searx/templates/simple/preferences.html
> +      <div class="description">{{ _('When enabled, the result page\'s title contains your query. Your browser can record this title.') }}</div>
fixed in 3f3097c7

2021-11-29 08:46 UTC, unixfox commented
![image](https://user-images.githubusercontent.com/4016501/143835657-d5690567-a2d6-4bc7-9b55-449f76a4fe23.png)

There is a space missing, not sure where to fix that 🤔

2021-11-29 10:28 UTC, return42 commented
> There is a space missing 

Discussion moved to https://github.com/searxng/searxng/pull/560