Simple theme svg2png
searxng/searxng pull request #541
Opened 2021-11-23 19:31 UTC by dalf

## What does this PR do?

In the master branch, convert (imagemagick) creates `searx/static/themes/simple/img/favicon.png` from `src/brand/searxng-wordmark.svg`. Some versions of convert have issues to render the .svg file.

This PR replaces the usage of convert by [sharp](https://github.com/lovell/sharp) (a standalone lib, it requires C++ to compile the library).

A custom grunt task is created because [grunt-task](https://www.npmjs.com/package/grunt-sharp) can't be installed (most probably because it hasn't been updated since a long time).

The "[build] /static" has been made using this change (the png file is smaller, it can be even smaller using [optipng](https://www.npmjs.com/package/optipng))

## Why is this change important?

Reliable build steps

## How to test this PR locally?

* `make themes.simple` or `npm run build`
* check `searx/static/themes/simple/img/favicon.png` is not modified (so `make static.build.commit` won't include the favicon at the build).
* check the favicon is rendered as expected.

## Author's checklist

## Related issues

2021-11-24 09:17 UTC, mrpaulblack approved these changes
LGTM

I tested with `make node.env` and `make themes.simple` and generated new favicon properly and droped it with `make static.build.restore`; also the image is rendered properly in my browser

2021-11-24 09:23 UTC, return42 commented
I am still in a review / please wait ...

2021-11-24 15:25 UTC, return42 requested changes
> it requires C++ to compile the library

Not on a _common_ build host, [Ready-compiled sharp and libvips binaries are provided for use on the most common platforms ... An ~7MB tarball containing libvips and its most commonly used dependencies is downloaded via HTTPS and stored within node_modules/sharp/vendor during npm install.](https://sharp.pixelplumbing.com/install#prebuilt-binaries)

> The "[build] /static" has been made using this change (the png file is smaller, it can be even smaller using optipng)

I missed the resize to 64x64 .. 5096 Byte --> 2747 Byte

I added commit 171f492c on top of your branch ...

    [mod] improve grunt task: svg2png / add resize options

.. it is my first Node.js implementation, please take a thorough look at it.

And I had some nits about reordering the tasks / see below.

2021-11-24 15:25 UTC, return42 commented on searx/static/themes/simple/gruntfile.js
> +        tasks: ['eslint', 'copy', 'concat', 'uglify', 'less:development', 'less:production', 'image', 'svg2png', 'svg2jinja']
nit: Reordering the items in the tasks list makes it hard to see what has been changed.  Are there any special reason to reorder the tasks?

2021-11-24 15:25 UTC, return42 commented on searx/static/themes/simple/gruntfile.js
> +    'svg2jinja',
see my comment above ..

> Reordering the items in the task list makes it hard to see what has been changed. Are there any special reason to reorder the tasks?

2021-11-24 15:25 UTC, return42 commented on searx/static/themes/simple/gruntfile.js
> -    },
see my comment above ..

> Reordering the items in the task list makes it hard to see what has been changed. Are there any special reason to reorder the tasks?

2021-11-24 15:25 UTC, return42 commented on searx/static/themes/simple/gruntfile.js
> +  grunt.registerMultiTask('svg2png', 'Convert SVG to PNG', function() {
Wow, very cool hadn't thought it is such easy :+1:

2021-11-24 15:25 UTC, return42 commented on searx/static/themes/simple/gruntfile.js
> +      const svgFileName = this.data.files[pngFileName];
I don't know what is common, but intuitive I would suggest to change "key" & "value" of the dictionary:  

    files[<src svg>]: "<dest png>" 
 
or even better a list of destinations:

    files[<src svg>]: ["<dest-1 png>", "<dest-2 png> ...] 

EDIT: done in 171f492c

2021-11-24 15:25 UTC, return42 commented on searx/static/themes/simple/gruntfile.js
> +          });
the `-resize 64x64` is missed here. (fixed in 171f492c)

2021-11-24 16:28 UTC, dalf commented on searx/static/themes/simple/gruntfile.js
> +      const svgFileName = this.data.files[pngFileName];
For these packages picked randomly:
* https://www.npmjs.com/package/grunt-image
* https://www.npmjs.com/package/grunt-svgmin
* https://www.npmjs.com/package/grunt-plantuml

Each time the pattern is:
```
{ "dest": "src" }
```

2021-11-24 16:30 UTC, dalf commented on searx/static/themes/simple/gruntfile.js
> +        tasks: ['eslint', 'copy', 'concat', 'uglify', 'less:development', 'less:production', 'image', 'svg2png', 'svg2jinja']
Sorry, I should have done that in another PR (in the master branch the JS and images are interleaved)
The purpose is to put all image tasks at the end with uniform patterns

2021-11-24 16:32 UTC, dalf commented on searx/static/themes/simple/gruntfile.js
> +            dest: [ 'img/favicon.png' ]
The pattern
```
        files: {
          'img/favicon.png': '<%= _brand %>/searxng-wordmark.svg'
        }
```
make it easy to read that `'<%= _brand %>/searxng-wordmark.svg'` is used in this task and the one just above.

2021-11-24 21:30 UTC, return42 commented on searx/static/themes/simple/gruntfile.js
> +        tasks: ['eslint', 'copy', 'concat', 'uglify', 'less:development', 'less:production', 'image', 'svg2png', 'svg2jinja']
> Sorry, the purpose is to put all image tasks at the end, where it is easy to list which image is processed. I should have done that in another PR.

I can split the one in two commit, if you want.

2021-11-25 09:34 UTC, return42 approved these changes
I separated ..

64228b69 [mod] gruntfile: do some polish (no functional change) 

from my side this PR is ready to merge / @dalf if don't see any issue more, please merge.

2021-11-27 19:21 UTC, dalf commented
I have added a commit to change 171f492

* the `svg2png` task define the files in a similar way to the `grunt-image` task:
   * https://github.com/searxng/searxng/blob/2109cfdfe45c76b20d9dd086a10719ef334841f9/searx/static/themes/simple/gruntfile.js#L150
   * https://github.com/searxng/searxng/blob/2109cfdfe45c76b20d9dd086a10719ef334841f9/searx/static/themes/simple/gruntfile.js#L157
* I removed the resize step: the size of the favicon image is 16x16 pixels, but the Firefox and other browsers display often used websites on a new tab. Without a [manifest.json endpoint](https://developer.mozilla.org/en-US/docs/Web/Manifest), the browser uses the favicon. A size of 16x16 will look pixelated. The current look is okay, so I removed the resize step:
![image](https://user-images.githubusercontent.com/1594191/143718915-ab9959ef-cb71-47e4-b3ae-750e47c16d11.png)
* on error, grunt stops the compilation (instead of displaying a warning).
* use `await` to simplify the code ( see https://github.com/1000ch/grunt-image/blob/master/tasks/image.js )

2021-11-28 11:33 UTC, return42 commented
> * the `svg2png` task define the files in a similar way to the `grunt-image` task: ...

OK

> * I removed the resize step: ...

I vote to get options back, ...

> Without a [manifest.json endpoint](https://developer.mozilla.org/en-US/docs/Web/Manifest), ...

With resize options we can easily create sizes, needed for a [manifest.json endpoint](https://developer.mozilla.org/en-US/docs/Web/Manifest) I can implement in another PR.

If it is OK for you to have resize options, would you like to add resize options and merge it with the two other commits / otherwise I can do it ..

2021-11-28 16:45 UTC, return42 commented
> I vote to get options back, ...

Resolution options are no longer needed, in PR https://github.com/searxng/searxng/pull/558 favicon is generated as SVG.

2021-11-28 19:12 UTC, return42 approved these changes
FYI: squashed the two commits into 59f4c792b and rebased on current master.

2021-11-28 19:13 UTC, merged